In [25]:
pip install gensim

Requirement already satisfied: gensim in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from gensim) (1.14.1)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from gensim) (7.3.1)
Requirement already satisfied: wrapt in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
import gensim
from gensim.models import word2vec,keyedvectors

In [27]:
import pandas as pd

messages=pd.read_csv('https://raw.githubusercontent.com/krishnaik06/Complete-Data-Science-With-Machine-Learning-And-NLP-2024/refs/heads/main/26-CompleteNLP%20For%20Machine%20Learning/Practicals/SpamClassifier-master/smsspamcollection/SMSSpamCollection',sep='\t')

messages

,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
0,ham,Ok lar... Joking wif u oni...
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...
2,ham,U dun say so early hor... U c already then say...
3,ham,"Nah I don't think he goes to usf, he lives aro..."
4,spam,FreeMsg Hey there darling it's been 3 week's n...
...,...,...
5566,spam,This is the 2nd time we have tried 2 contact u...
5567,ham,Will ü b going to esplanade fr home?
5568,ham,"Pity, * was in mood for that. So...any other s..."
5569,ham,The guy did some bitching but I acted like i'd...
5570,ham,Rofl. Its true to its name

In [28]:
from nltk.stem import WordNetLemmatizer

lemmatizer=WordNetLemmatizer()

In [29]:
import re

from nltk.corpus import stopwords

In [30]:
messages.columns=['label','message']

In [31]:
corpus=[]
for i in range(len(messages)):
    review=re.sub(r"[^a-zA-Z]"," ",messages['message'][i]) #keeping only characters in sentences
    review=review.lower() #lowercasing the words
    review=review.split()
    
    review=[lemmatizer.lemmatize(word) for word in review]
    corpus.append(review)

print(corpus)

[['ok', 'lar', 'joking', 'wif', 'u', 'oni'], ['free', 'entry', 'in', 'a', 'wkly', 'comp', 'to', 'win', 'fa', 'cup', 'final', 'tkts', 'st', 'may', 'text', 'fa', 'to', 'to', 'receive', 'entry', 'question', 'std', 'txt', 'rate', 't', 'c', 's', 'apply', 'over', 's'], ['u', 'dun', 'say', 'so', 'early', 'hor', 'u', 'c', 'already', 'then', 'say'], ['nah', 'i', 'don', 't', 'think', 'he', 'go', 'to', 'usf', 'he', 'life', 'around', 'here', 'though'], ['freemsg', 'hey', 'there', 'darling', 'it', 's', 'been', 'week', 's', 'now', 'and', 'no', 'word', 'back', 'i', 'd', 'like', 'some', 'fun', 'you', 'up', 'for', 'it', 'still', 'tb', 'ok', 'xxx', 'std', 'chgs', 'to', 'send', 'to', 'rcv'], ['even', 'my', 'brother', 'is', 'not', 'like', 'to', 'speak', 'with', 'me', 'they', 'treat', 'me', 'like', 'aid', 'patent'], ['a', 'per', 'your', 'request', 'melle', 'melle', 'oru', 'minnaminunginte', 'nurungu', 'vettam', 'ha', 'been', 'set', 'a', 'your', 'callertune', 'for', 'all', 'caller', 'press', 'to', 'copy', 'your', 'friend', 'callertune'], ['winner', 'a', 'a', 'valued', 'network', 'customer', 'you', 'have', 'been', 'selected', 'to', 'receivea', 'prize', 'reward', 'to', 'claim', 'call', 'claim', 'code', 'kl', 'valid', 'hour', 'only'], ['had', 'your', 'mobile', 'month', 'or', 'more', 'u', 'r', 'entitled', 'to', 'update', 'to', 'the', 'latest', 'colour', 'mobile', 'with', 'camera', 'for', 'free', 'call', 'the', 'mobile', 'update', 'co', 'free', 'on'], ['i', 'm', 'gonna', 'be', 'home', 'soon', 'and', 'i', 'don', 't', 'want', 'to', 'talk', 'about', 'this', 'stuff', 'anymore', 'tonight', 'k', 'i', 've', 'cried', 'enough', 'today'], ['six', 'chance', 'to', 'win', 'cash', 'from', 'to', 'pound', 'txt', 'csh', 'and', 'send', 'to', 'cost', 'p', 'day', 'day', 'tsandcs', 'apply', 'reply', 'hl', 'info'], ['urgent', 'you', 'have', 'won', 'a', 'week', 'free', 'membership', 'in', 'our', 'prize', 'jackpot', 'txt', 'the', 'word', 'claim', 'to', 'no', 't', 'c', 'www', 'dbuk', 'net', 'lccltd', 'pobox', 'ldnw', 'a', 'rw'], ['i', 've', 'been', 'searching', 'for', 'the', 'right', 'word', 'to', 'thank', 'you', 'for', 'this', 'breather', 'i', 'promise', 'i', 'wont', 'take', 'your', 'help', 'for', 'granted', 'and', 'will', 'fulfil', 'my', 'promise', 'you', 'have', 'been', 'wonderful', 'and', 'a', 'blessing', 'at', 'all', 'time'], ['i', 'have', 'a', 'date', 'on', 'sunday', 'with', 'will'], ['xxxmobilemovieclub', 'to', 'use', 'your', 'credit', 'click', 'the', 'wap', 'link', 'in', 'the', 'next', 'txt', 'message', 'or', 'click', 'here', 'http', 'wap', 'xxxmobilemovieclub', 'com', 'n', 'qjkgighjjgcbl'], ['oh', 'k', 'i', 'm', 'watching', 'here'], ['eh', 'u', 'remember', 'how', 'spell', 'his', 'name', 'yes', 'i', 'did', 'he', 'v', 'naughty', 'make', 'until', 'i', 'v', 'wet'], ['fine', 'if', 'that', 's', 'the', 'way', 'u', 'feel', 'that', 's', 'the', 'way', 'it', 'gota', 'b'], ['england', 'v', 'macedonia', 'dont', 'miss', 'the', 'goal', 'team', 'news', 'txt', 'ur', 'national', 'team', 'to', 'eg', 'england', 'to', 'try', 'wale', 'scotland', 'txt', 'poboxox', 'w', 'wq'], ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name'], ['i', 'm', 'going', 'to', 'try', 'for', 'month', 'ha', 'ha', 'only', 'joking'], ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'], ['aft', 'i', 'finish', 'my', 'lunch', 'then', 'i', 'go', 'str', 'down', 'lor', 'ard', 'smth', 'lor', 'u', 'finish', 'ur', 'lunch', 'already'], ['ffffffffff', 'alright', 'no', 'way', 'i', 'can', 'meet', 'up', 'with', 'you', 'sooner'], ['just', 'forced', 'myself', 'to', 'eat', 'a', 'slice', 'i', 'm', 'really', 'not', 'hungry', 'tho', 'this', 'suck', 'mark', 'is', 'getting', 'worried', 'he', 'know', 'i', 'm', 'sick', 'when', 'i', 'turn', 'down', 'pizza', 'lol'], ['lol', 'your', 'always', 'so', 'convincing'], ['did', 'you', 'catch', 'the', 'bus', 'are', 'you', 'frying', 'an', 'egg', 'did', 'you', 'make', 'a', 'tea', 'are', 'you', 'eating', 'your', 'mom', 's', 'left', 'over', 'dinner', 'do', 'you', 'feel', 'my', 'love'], ['i', 'm', 'back', 'amp', 'we', 're', 'packing', 'the', 'car', 'now', 'i', 'll', 'let', 'you', 'know', 'if', 'there', 's', 'room'], ['ahhh', 'work', 'i', 'vaguely', 'remember', 'that', 'what', 'doe', 'it', 'feel', 'like', 'lol'], ['wait', 'that', 's', 'still', 'not', 'all', 'that', 'clear', 'were', 'you', 'not', 'sure', 'about', 'me', 'being', 'sarcastic', 'or', 'that', 'that', 's', 'why', 'x', 'doesn', 't', 'want', 'to', 'live', 'with', 'u'], ['yeah', 'he', 'got', 'in', 'at', 'and', 'wa', 'v', 'apologetic', 'n', 'had', 'fallen', 'out', 'and', 'she', 'wa', 'actin', 'like', 'spoilt', 'child', 'and', 'he', 'got', 'caught', 'up', 'in', 'that', 'till', 'but', 'we', 'won', 't', 'go', 'there', 'not', 'doing', 'too', 'badly', 'cheer', 'you'], ['k', 'tell', 'me', 'anything', 'about', 'you'], ['for', 'fear', 'of', 'fainting', 'with', 'the', 'of', 'all', 'that', 'housework', 'you', 'just', 'did', 'quick', 'have', 'a', 'cuppa'], ['thanks', 'for', 'your', 'subscription', 'to', 'ringtone', 'uk', 'your', 'mobile', 'will', 'be', 'charged', 'month', 'please', 'confirm', 'by', 'replying', 'yes', 'or', 'no', 'if', 'you', 'reply', 'no', 'you', 'will', 'not', 'be', 'charged'], ['yup', 'ok', 'i', 'go', 'home', 'look', 'at', 'the', 'timing', 'then', 'i', 'msg', 'again', 'xuhui', 'going', 'to', 'learn', 'on', 'nd', 'may', 'too', 'but', 'her', 'lesson', 'is', 'at', 'am'], ['oops', 'i', 'll', 'let', 'you', 'know', 'when', 'my', 'roommate', 's', 'done'], ['i', 'see', 'the', 'letter', 'b', 'on', 'my', 'car'], ['anything', 'lor', 'u', 'decide'], ['hello', 'how', 's', 'you', 'and', 'how', 'did', 'saturday', 'go', 'i', 'wa', 'just', 'texting', 'to', 'see', 'if', 'you', 'd', 'decided', 'to', 'do', 'anything', 'tomo', 'not', 'that', 'i', 'm', 'trying', 'to', 'invite', 'myself', 'or', 'anything'], ['pls', 'go', 'ahead', 'with', 'watt', 'i', 'just', 'wanted', 'to', 'be', 'sure', 'do', 'have', 'a', 'great', 'weekend', 'abiola'], ['did', 'i', 'forget', 'to', 'tell', 'you', 'i', 'want', 'you', 'i', 'need', 'you', 'i', 'crave', 'you', 'but', 'most', 'of', 'all', 'i', 'love', 'you', 'my', 'sweet', 'arabian', 'steed', 'mmmmmm', 'yummy'], ['rodger', 'burn', 'msg', 'we', 'tried', 'to', 'call', 'you', 're', 'your', 'reply', 'to', 'our', 'sm', 'for', 'a', 'free', 'nokia', 'mobile', 'free', 'camcorder', 'please', 'call', 'now', 'for', 'delivery', 'tomorrow'], ['who', 'are', 'you', 'seeing'], ['great', 'i', 'hope', 'you', 'like', 'your', 'man', 'well', 'endowed', 'i', 'am', 'lt', 'gt', 'inch'], ['no', 'call', 'message', 'missed', 'call'], ['didn', 't', 'you', 'get', 'hep', 'b', 'immunisation', 'in', 'nigeria'], ['fair', 'enough', 'anything', 'going', 'on'], ['yeah', 'hopefully', 'if', 'tyler', 'can', 't', 'do', 'it', 'i', 'could', 'maybe', 'ask', 'around', 'a', 'bit'], ['u', 'don', 't', 'know', 'how', 'stubborn', 'i', 'am', 'i', 'didn', 't', 'even', 'want', 'to', 'go', 'to', 'the', 'hospital', 'i', 'kept', 'telling', 'mark', 'i', 'm', 'not', 'a', 'weak', 'sucker', 'hospital', 'are', 'for', 'weak', 'sucker'], ['what', 'you', 'thinked', 'about', 'me', 'first', 'time', 'you', 'saw', 'me', 'in', 'class'], ['a', 'gram', 'usually', 'run', 'like', 'lt', 'gt', 'a', 'half', 'eighth', 'is', 'smarter', 'though', 'and', 'get', 'you', 'almost', 'a', 'whole', 'second', 'gram', 'for', 'lt', 'gt'], ['k', 'fyi', 'x', 'ha', 'a', 'ride', 'early', 'tomorrow', 'morning', 'but', 'he', 's', 'crashing', 'at', 'our', 'place', 'tonight'], ['wow', 'i', 'never', 'realized', 'that', 'you', 'were', 'so', 'embarassed', 'by', 'your', 'accomodations', 'i', 'thought', 'you', 'liked', 'it', 'since', 'i', 'wa', 'doing', 'the', 'best', 'i', 'could', 'and', 'you', 'always', 'seemed', 'so', 'happy', 'about', 'the', 'cave', 'i', 'm', 'sorry', 'i', 'didn', 't', 'and', 'don', 't', 'have', 'more', 'to', 'give', 'i', 'm', 'sorry', 'i', 'offered', 'i', 'm', 'sorry', 'your', 'room', 'wa', 'so', 'embarassing'], ['sm', 'ac', 'sptv', 'the', 'new', 'jersey', 'devil', 'and', 'the', 'detroit', 'red', 'wing', 'play', 'ice', 'hockey', 'correct', 'or', 'incorrect', 'end', 'reply', 'end', 'sptv'], ['do', 'you', 'know', 'what', 'mallika', 'sherawat', 'did', 'yesterday', 'find', 'out', 'now', 'lt', 'url', 'gt'], ['congrats', 'year', 'special', 'cinema', 'pas', 'for', 'is', 'yours', 'call', 'now', 'c', 'suprman', 'v', 'matrix', 'starwars', 'etc', 'all', 'free', 'bx', 'ip', 'we', 'pm', 'dont', 'miss', 'out'], ['sorry', 'i', 'll', 'call', 'later', 'in', 'meeting'], ['tell', 'where', 'you', 'reached'], ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'], ['your', 'gonna', 'have', 'to', 'pick', 'up', 'a', 'burger', 'for', 'yourself', 'on', 'your', 'way', 'home', 'i', 'can', 't', 'even', 'move', 'pain', 'is', 'killing', 'me'], ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seeker'], ['it', 'a', 'part', 'of', 'checking', 'iq'], ['sorry', 'my', 'roommate', 'took', 'forever', 'it', 'ok', 'if', 'i', 'come', 'by', 'now'], ['ok', 'lar', 'i', 'double', 'check', 'wif', 'da', 'hair', 'dresser', 'already', 'he', 'said', 'wun', 'cut', 'v', 'short', 'he', 'said', 'will', 'cut', 'until', 'i', 'look', 'nice'], ['a', 'a', 'valued', 'customer', 'i', 'am', 'pleased', 'to', 'advise', 'you', 'that', 'following', 'recent', 'review', 'of', 'your', 'mob', 'no', 'you', 'are', 'awarded', 'with', 'a', 'bonus', 'prize', 'call'], ['today', 'is', 'song', 'dedicated', 'day', 'which', 'song', 'will', 'u', 'dedicate', 'for', 'me', 'send', 'this', 'to', 'all', 'ur', 'valuable', 'frnds', 'but', 'first', 'rply', 'me'], ['urgent', 'ur', 'awarded', 'a', 'complimentary', 'trip', 'to', 'eurodisinc', 'trav', 'aco', 'entry', 'or', 'to', 'claim', 'txt', 'dis', 'to', 'morefrmmob', 'shracomorsglsuplt', 'l', 'aj'], ['did', 'you', 'hear', 'about', 'the', 'new', 'divorce', 'barbie', 'it', 'come', 'with', 'all', 'of', 'ken', 's', 'stuff'], ['i', 'plane', 'to', 'give', 'on', 'this', 'month', 'end'], ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'], ['finished', 'class', 'where', 'are', 'you'], ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'], ['k', 'k', 'where', 'are', 'you', 'how', 'did', 'you', 'performed'], ['u', 'can', 'call', 'me', 'now'], ['i', 'am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'], ['thats', 'cool', 'i', 'am', 'a', 'gentleman', 'and', 'will', 'treat', 'you', 'with', 'dignity', 'and', 'respect'], ['i', 'like', 'you', 'people', 'very', 'much', 'but', 'am', 'very', 'shy', 'pa'], ['doe', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'], ['it', 'not', 'the', 'same', 'here', 'still', 'looking', 'for', 'a', 'job', 'how', 'much', 'do', 'ta', 's', 'earn', 'there'], ['sorry', 'i', 'll', 'call', 'later'], ['k', 'did', 'you', 'call', 'me', 'just', 'now', 'ah'], ['ok', 'i', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'], ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'], ['yup', 'next', 'stop'], ['i', 'call', 'you', 'later', 'don', 't', 'have', 'network', 'if', 'urgnt', 'sm', 'me'], ['for', 'real', 'when', 'u', 'getting', 'on', 'yo', 'i', 'only', 'need', 'more', 'ticket', 'and', 'one', 'more', 'jacket', 'and', 'i', 'm', 'done', 'i', 'already', 'used', 'all', 'my', 'multis'], ['yes', 'i', 'started', 'to', 'send', 'request', 'to', 'make', 'it', 'but', 'pain', 'came', 'back', 'so', 'i', 'm', 'back', 'in', 'bed', 'double', 'coin', 'at', 'the', 'factory', 'too', 'i', 'gotta', 'cash', 'in', 'all', 'my', 'nitros'], ['i', 'm', 'really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'], ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'], ['yeah', 'do', 'don', 't', 'stand', 'to', 'close', 'tho', 'you', 'll', 'catch', 'something'], ['sorry', 'to', 'be', 'a', 'pain', 'is', 'it', 'ok', 'if', 'we', 'meet', 'another', 'night', 'i', 'spent', 'late', 'afternoon', 'in', 'casualty', 'and', 'that', 'mean', 'i', 'haven', 't', 'done', 'any', 'of', 'y', 'stuff', 'moro', 'and', 'that', 'includes', 'all', 'my', 'time', 'sheet', 'and', 'that', 'sorry'], ['smile', 'in', 'pleasure', 'smile', 'in', 'pain', 'smile', 'when', 'trouble', 'pours', 'like', 'rain', 'smile', 'when', 'sum', 'hurt', 'u', 'smile', 'becoz', 'someone', 'still', 'love', 'to', 'see', 'u', 'smiling'], ['please', 'call', 'our', 'customer', 'service', 'representative', 'on', 'between', 'am', 'pm', 'a', 'you', 'have', 'won', 'a', 'guaranteed', 'cash', 'or', 'prize'], ['havent', 'planning', 'to', 'buy', 'later', 'i', 'check', 'already', 'lido', 'only', 'got', 'show', 'in', 'e', 'afternoon', 'u', 'finish', 'work', 'already'], ['your', 'free', 'ringtone', 'is', 'waiting', 'to', 'be', 'collected', 'simply', 'text', 'the', 'password', 'mix', 'to', 'to', 'verify', 'get', 'usher', 'and', 'britney', 'fml', 'po', 'box', 'mk', 'h', 'ppw'], ['watching', 'telugu', 'movie', 'wat', 'abt', 'u'], ['i', 'see', 'when', 'we', 'finish', 'we', 'have', 'load', 'of', 'loan', 'to', 'pay'], ['hi', 'wk', 'been', 'ok', 'on', 'hols', 'now', 'yes', 'on', 'for', 'a', 'bit', 'of', 'a', 'run', 'forgot', 'that', 'i', 'have', 'hairdresser', 'appointment', 'at', 'four', 'so', 'need', 'to', 'get', 'home', 'n', 'shower', 'beforehand', 'doe', 'that', 'cause', 'prob', 'for', 'u'], ['i', 'see', 'a', 'cup', 'of', 'coffee', 'animation'], ['please', 'don', 't', 'text', 'me', 'anymore', 'i', 'have', 'nothing', 'else', 'to', 'say'], ['okay', 'name', 'ur', 'price', 'a', 'long', 'a', 'it', 'legal', 'wen', 'can', 'i', 'pick', 'them', 'up', 'y', 'u', 'ave', 'x', 'am', 'xx'], ['i', 'm', 'still', 'looking', 'for', 'a', 'car', 'to', 'buy', 'and', 'have', 'not', 'gone', 'the', 'driving', 'test', 'yet'], ['a', 'per', 'your', 'request', 'melle', 'melle', 'oru', 'minnaminunginte', 'nurungu', 'vettam', 'ha', 'been', 'set', 'a', 'your', 'callertune', 'for', 'all', 'caller', 'press', 'to', 'copy', 'your', 'friend', 'callertune'], ['wow', 'you', 're', 'right', 'i', 'didn', 't', 'mean', 'to', 'do', 'that', 'i', 'guess', 'once', 'i', 'gave', 'up', 'on', 'boston', 'men', 'and', 'changed', 'my', 'search', 'location', 'to', 'nyc', 'something', 'changed', 'cuz', 'on', 'my', 'signin', 'page', 'it', 'still', 'say', 'boston'], ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'], ['thanks', 'a', 'lot', 'for', 'your', 'wish', 'on', 'my', 'birthday', 'thanks', 'you', 'for', 'making', 'my', 'birthday', 'truly', 'memorable'], ['aight', 'i', 'll', 'hit', 'you', 'up', 'when', 'i', 'get', 'some', 'cash'], ['how', 'would', 'my', 'ip', 'address', 'test', 'that', 'considering', 'my', 'computer', 'isn', 't', 'a', 'minecraft', 'server'], ['i', 'know', 'grumpy', 'old', 'people', 'my', 'mom', 'wa', 'like', 'you', 'better', 'not', 'be', 'lying', 'then', 'again', 'i', 'am', 'always', 'the', 'one', 'to', 'play', 'joke'], ['dont', 'worry', 'i', 'guess', 'he', 's', 'busy'], ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'], ['going', 'for', 'dinner', 'msg', 'you', 'after'], ['i', 'm', 'ok', 'wif', 'it', 'co', 'i', 'like', 'try', 'new', 'thing', 'but', 'i', 'scared', 'u', 'dun', 'like', 'mah', 'co', 'u', 'said', 'not', 'too', 'loud'], ['gent', 'we', 'are', 'trying', 'to', 'contact', 'you', 'last', 'weekend', 'draw', 'show', 'that', 'you', 'won', 'a', 'prize', 'guaranteed', 'call', 'claim', 'code', 'k', 'valid', 'hr', 'only', 'ppm'], ['wa', 'ur', 'openin', 'sentence', 'very', 'formal', 'anyway', 'i', 'm', 'fine', 'too', 'juz', 'tt', 'i', 'm', 'eatin', 'too', 'much', 'n', 'puttin', 'on', 'weight', 'haha', 'so', 'anythin', 'special', 'happened'], ['a', 'i', 'entered', 'my', 'cabin', 'my', 'pa', 'said', 'happy', 'b', 'day', 'bos', 'i', 'felt', 'special', 'she', 'askd', 'me', 'lunch', 'after', 'lunch', 'she', 'invited', 'me', 'to', 'her', 'apartment', 'we', 'went', 'there'], ['you', 'are', 'a', 'winner', 'u', 'have', 'been', 'specially', 'selected', 'receive', 'or', 'a', 'holiday', 'flight', 'inc', 'speak', 'to', 'a', 'live', 'operator', 'claim', 'p', 'min'], ['goodo', 'yes', 'we', 'must', 'speak', 'friday', 'egg', 'potato', 'ratio', 'for', 'tortilla', 'needed'], ['hmm', 'my', 'uncle', 'just', 'informed', 'me', 'that', 'he', 's', 'paying', 'the', 'school', 'directly', 'so', 'pls', 'buy', 'food'], ['private', 'your', 'account', 'statement', 'for', 'show', 'unredeemed', 'bonus', 'point', 'to', 'claim', 'call', 'identifier', 'code', 'expires'], ['urgent', 'your', 'mobile', 'no', 'wa', 'awarded', 'bonus', 'caller', 'prize', 'on', 'this', 'is', 'our', 'final', 'try', 'to', 'contact', 'u', 'call', 'from', 'landline', 'box', 'wr', 'c', 'ppm'], ['here', 'is', 'my', 'new', 'address', 'apple', 'pair', 'all', 'that', 'malarky'], ['today', 'voda', 'number', 'ending', 'are', 'selected', 'to', 'receive', 'a', 'award', 'if', 'you', 'have', 'a', 'match', 'please', 'call', 'quoting', 'claim', 'code', 'standard', 'rate', 'app'], ['i', 'am', 'going', 'to', 'sao', 'mu', 'today', 'will', 'be', 'done', 'only', 'at'], ['predict', 'wat', 'time', 'll', 'finish', 'buying'], ['good', 'stuff', 'will', 'do'], ['just', 'so', 'that', 'you', 'know', 'yetunde', 'hasn', 't', 'sent', 'money', 'yet', 'i', 'just', 'sent', 'her', 'a', 'text', 'not', 'to', 'bother', 'sending', 'so', 'it', 'over', 'you', 'dont', 'have', 'to', 'involve', 'yourself', 'in', 'anything', 'i', 'shouldn', 't', 'have', 'imposed', 'anything', 'on', 'you', 'in', 'the', 'first', 'place', 'so', 'for', 'that', 'i', 'apologise'], ['are', 'you', 'there', 'in', 'room'], ['hey', 'girl', 'how', 'r', 'u', 'hope', 'u', 'r', 'well', 'me', 'an', 'del', 'r', 'bak', 'again', 'long', 'time', 'no', 'c', 'give', 'me', 'a', 'call', 'sum', 'time', 'from', 'lucyxx'], ['k', 'k', 'how', 'much', 'doe', 'it', 'cost'], ['i', 'm', 'home'], ['dear', 'will', 'call', 'tmorrow', 'pls', 'accomodate'], ['first', 'answer', 'my', 'question'], ['sunshine', 'quiz', 'wkly', 'q', 'win', 'a', 'top', 'sony', 'dvd', 'player', 'if', 'u', 'know', 'which', 'country', 'the', 'algarve', 'is', 'in', 'txt', 'ansr', 'to', 'sp', 'tyrone'], ['want', 'get', 'laid', 'tonight', 'want', 'real', 'dogging', 'location', 'sent', 'direct', 'ur', 'mob', 'join', 'the', 'uk', 's', 'largest', 'dogging', 'network', 'bt', 'txting', 'gravel', 'to', 'nt', 'ec', 'a', 'p', 'msg', 'p'], ['i', 'only', 'haf', 'msn', 'it', 's', 'yijue', 'hotmail', 'com'], ['he', 'is', 'there', 'you', 'call', 'and', 'meet', 'him'], ['no', 'no', 'i', 'will', 'check', 'all', 'room', 'befor', 'activity'], ['you', 'll', 'not', 'rcv', 'any', 'more', 'msg', 'from', 'the', 'chat', 'svc', 'for', 'free', 'hardcore', 'service', 'text', 'go', 'to', 'if', 'u', 'get', 'nothing', 'u', 'must', 'age', 'verify', 'with', 'yr', 'network', 'try', 'again'], ['got', 'c', 'i', 'lazy', 'to', 'type', 'i', 'forgot', 'in', 'lect', 'i', 'saw', 'a', 'pouch', 'but', 'like', 'not', 'v', 'nice'], ['k', 'text', 'me', 'when', 'you', 're', 'on', 'the', 'way'], ['sir', 'waiting', 'for', 'your', 'mail'], ['a', 'swt', 'thought', 'nver', 'get', 'tired', 'of', 'doing', 'little', 'thing', 'lovable', 'person', 'coz', 'somtimes', 'those', 'little', 'thing', 'occupy', 'd', 'biggest', 'part', 'in', 'their', 'heart', 'gud', 'ni'], ['i', 'know', 'you', 'are', 'can', 'you', 'pls', 'open', 'the', 'back'], ['yes', 'see', 'ya', 'not', 'on', 'the', 'dot'], ['whats', 'the', 'staff', 'name', 'who', 'is', 'taking', 'class', 'for', 'u'], ['freemsg', 'why', 'haven', 't', 'you', 'replied', 'to', 'my', 'text', 'i', 'm', 'randy', 'sexy', 'female', 'and', 'live', 'local', 'luv', 'to', 'hear', 'from', 'u', 'netcollex', 'ltd', 'p', 'per', 'msg', 'reply', 'stop', 'to', 'end'], ['ummma', 'will', 'call', 'after', 'check', 'in', 'our', 'life', 'will', 'begin', 'from', 'qatar', 'so', 'pls', 'pray', 'very', 'hard'], ['k', 'i', 'deleted', 'my', 'contact', 'that', 'why'], ['sindu', 'got', 'job', 'in', 'birla', 'soft'], ['the', 'wine', 'is', 'flowing', 'and', 'i', 'm', 'i', 'have', 'nevering'], ['yup', 'i', 'thk', 'cine', 'is', 'better', 'co', 'no', 'need', 'go', 'down', 'plaza', 'mah'], ['ok', 'ur', 'typical', 'reply'], ['a', 'per', 'your', 'request', 'melle', 'melle', 'oru', 'minnaminunginte', 'nurungu', 'vettam', 'ha', 'been', 'set', 'a', 'your

In [32]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, [], '645'], [0, [], ':) '], [0, [], ':-) :-)']]

In [33]:
corpus

[['ok', 'lar', 'joking', 'wif', 'u', 'oni'],
 ['free',
  'entry',
  'in',
  'a',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  't',
  'c',
  's',
  'apply',
  'over',
  's'],
 ['u', 'dun', 'say', 'so', 'early', 'hor', 'u', 'c', 'already', 'then', 'say'],
 ['nah',
  'i',
  'don',
  't',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  's',
  'been',
  'week',
  's',
  'now',
  'and',
  'no',
  'word',
  'back',
  'i',
  'd',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['a',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'a',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['winner',
  'a',
  'a',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour',
  'only'],
 ['had',
  'your',
  'mobile',
  'month',
  'or',
  'more',
  'u',
  'r',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobile',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on'],
 ['i',
  'm',
  'gonna',
  'be',
  'home',
  'soon',
  'and',
  'i',
  'don',
  't',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  'k',
  'i',
  've',
  'cried',
  'enough',
  'today'],
 ['six',
  'chance',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'p',
  'day',
  'day',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'you',
  'have',
  'won',
  'a',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  't',
  'c',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'a',
  'rw'],
 ['i',
  've',
  'been',
  'searching',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'i',
  'promise',
  'i',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'a',
  'blessing',
  'at',
  'all',
  'time'],
 ['i', 'have', 'a', 'date', 'on', 'sunday', 'with', 'will'],
 ['xxxmobilemovieclub',
  'to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'xxxmobilemovieclub',
  'com',
  'n',
  'qjkgighjjgcbl'],
 ['oh', 'k', 'i', 'm', 'watching', 'here'],
 ['eh',
  'u',
  'remember',
  'how',
  'spell',
  'his',
  'name',
  'yes',
  'i',
  'did',
  'he',
  'v',
  'naughty',
  'make',
  'until',
  'i',
  'v',
  'wet'],
 ['fine',
  'if',
  'that',
  's',
  'the',
  'way',
  'u',
  'feel',
  'that',
  's',
  'the',
  'way',
  'it',
  'gota',
  'b'],
 ['england',
  'v',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'try',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'w',
  'wq'],
 ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name'],
 ['i',
  'm',
  'going',
  'to',
  'try',
  'for',
  'month',
  'ha',
  'ha',
  'only',
  'joking'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['aft',
  'i',
  'finish',
  'my',
  'lunch',
  'then',
  'i',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'u',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'i',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['just',
  'forced',
  'myself',
  'to',
  'eat',
  'a',
  'slice',
  'i',
  'm',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'suck',
  'mark',
  'is',
  'getting',
  'worried',
  'he',
  'know',
  'i',
  'm',
  'sick',
  'when',
  'i',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convincing'],
 ['did',
  'you',
  'catch',
  'the',
  'bus',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  'did',
  'you',
  'make',
  'a',
  'tea',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  's',
  'left',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['i',
  'm',
  'back',
  'amp',
  'we',
  're',
  'packing',
  'the',
  'car',
  'now',
  'i',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  's',
  'room'],
 ['ahhh',
  'work',
  'i',
  'vaguely',
  'remember',
  'that',
  'what',
  'doe',
  'it',
  'feel',
  'like',
  'lol'],
 ['wait',
  'that',
  's',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  's',
  'why',
  'x',
  'doesn',
  't',
  'want',
  'to',
  'live',
  'with',
  'u'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  'and',
  'wa',
  'v',
  'apologetic',
  'n',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'wa',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'won',
  't',
  'go',
  'there',
  'not',
  'doing',
  'too',
  'badly',
  'cheer',
  'you'],
 ['k', 'tell', 'me', 'anything', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  'quick',
  'have',
  'a',
  'cuppa'],
 ['thanks',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  'month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['yup',
  'ok',
  'i',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timing',
  'then',
  'i',
  'msg',
  'again',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  'am'],
 ['oops',
  'i',
  'll',
  'let',
  'you',
  'know',
  'when',
  'my',
  'roommate',
  's',
  'done'],
 ['i', 'see', 'the', 'letter', 'b', 'on', 'my', 'car'],
 ['anything', 'lor', 'u', 'decide'],
 ['hello',
  'how',
  's',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  'i',
  'wa',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'd',
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'i',
  'm',
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watt',
  'i',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'a',
  'great',
  'weekend',
  'abiola'],
 ['did',
  'i',
  'forget',
  'to',
  'tell',
  'you',
  'i',
  'want',
  'you',
  'i',
  'need',
  'you',
  'i',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'i',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sm',
  'for',
  'a',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'are', 'you', 'seeing'],
 ['great',
  'i',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  'i',
  'am',
  'lt',
  'gt',
  'inch'],
 ['no', 'call', 'message', 'missed', 'call'],
 ['didn', 't', 'you', 'get', 'hep', 'b', 'immunisation', 'in', 'nigeria'],
 ['fair', 'enough', 'anything', 'going', 'on'],
 ['yeah',
  'hopefully',
  'if',
  'tyler',
  'can',
  't',
  'do',
  'it',
  'i',
  'could',
  'maybe',
  'ask',
  'around',
  'a',
  'bit'],
 ['u',
  'don',
  't',
  'know',
  'how',
  'stubborn',
  'i',
  'am',
  'i',
  'didn',
  't',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'i',
  'kept',
  'telling',
  'mark',
  'i',
  'm',
  'not',
  'a',
  'weak',
  'sucker',
  'hospital',
  'are',
  'for',
  'weak',
  'sucker'],
 ['what',
  'you',
  'thinked',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['a',
  'gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'a',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'a',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['k',
  'fyi',
  'x',
  'ha',
  'a',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  's',
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'i',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'i',
  'thought',
  'you',
  'liked',
  'it',
  'since',
  'i',
  'wa',
  'doing',
  'the',
  'best',
  'i',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'i',
  'm',
  'sorry',
  'i',
  'didn',
  't',
  'and',
  'don',
  't',
  'have',
  'more',
  'to',
  'give',
  'i',
  'm',
  'sorry',
  'i',
  'offered',
  'i',
  'm',
  'sorry',
  'your',
  'room',
  'wa',
  'so',
  'embarassing'],
 ['sm',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pas',
  'for',
  'is',
  'yours',
  'call',
  'now',
  'c',
  'suprman',
  'v',
  'matrix',
  'starwars',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['sorry', 'i', 'll', 'call', 'later', 'in', 'meeting'],
 ['tell', 'where', 'you', 'reached'],
 ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'a',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'i',
  'can',
  't',
  'even',
  'move',
  'pain',
  'is',
  'killing',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seeker'],
 ['it', 'a', 'part', 'of', 'checking', 'iq'],
 ['sorry',
  'my',
  'roommate',
  'took',
  'forever',
  'it',
  'ok',
  'if',
  'i',
  'come',
  'by',
  'now'],
 ['ok',
  'lar',
  'i',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'v',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'i',
  'look',
  'nice'],
 ['a',
  'a',
  'valued',
  'customer',
  'i',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'awarded',
  'with',
  'a',
  'bonus',
  'prize',
  'call'],
 ['today',
  'is',
  'song',
  'dedicated',
  'day',
  'which',
  'song',
  'will',
  'u',
  'dedicate',
  'for',
  'me',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['urgent',
  'ur',
  'awarded',
  'a',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'or',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  'morefrmmob',
  'shracomorsglsuplt',
  'l',
  'aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  's',
  'stuff'],
 ['i', 'plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finished', 'class', 'where', 'are', 'you'],
 ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'],
 ['k', 'k', 'where', 'are', 'you', 'how', 'did', 'you', 'performed'],
 ['u', 'can', 'call', 'me', 'now'],
 ['i', 'am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['thats',
  'cool',
  'i',
  'am',
  'a',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['i',
  'like',
  'you',
  'people',
  'very',
  'much',
  'but',
  'am',
  'very',
  'shy',
  'pa'],
 ['doe', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'],
 ['it',
  'not',
  'the',
  'same',
  'here',
  'still',
  'looking',
  'for',
  'a',
  'job',
  'how',
  'much',
  'do',
  'ta',
  's',
  'earn',
  'there'],
 ['sorry', 'i', 'll', 'call', 'later'],
 ['k', 'did', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['ok', 'i', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['i',
  'call',
  'you',
  'later',
  'don',
  't',
  'have',
  'network',
  'if',
  'urgnt',
  'sm',
  'me'],
 ['for',
  'real',
  'when',
  'u',
  'getting',
  'on',
  'yo',
  'i',
  'only',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'i',
  'm',
  'done',
  'i',
  'already',
  'used',
  'all',
  'my',
  'multis'],
 ['yes',
  'i',
  'started',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'i',
  'm',
  'back',
  'in',
  'bed',
  'double',
  'coin',
  'at',
  'the',
  'factory',
  'too',
  'i',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['i', 'm', 'really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  'don',
  't',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something'],
 ['sorry',
  'to',
  'be',
  'a',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  'i',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'mean',
  'i',
  'haven',
  't',
  'done',
  'any',
  'of',
  'y',
  'stuff',
  'moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorry'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'u',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'to',
  'see',
  'u',
  'smiling'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  'between',
  'am',
  'pm',
  'a',
  'you',
  'have',
  'won',
  'a',
  'guaranteed',
  'cash',
  'or',
  'prize'],
 ['havent',
  'planning',
  'to',
  'buy',
  'later',
  'i',
  'check',
  'already',
  'lido',
  'only',
  'got',
  'show',
  'in',
  'e',
  'afternoon',
  'u',
  'finish',
  'work',
  'already'],
 ['your',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'h',
  'ppw'],
 ['watching', 'telugu', 'movie', 'wat', 'abt', 'u'],
 ['i',
  'see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['hi',
  'wk',
  'been',
  'ok',
  'on',
  'hols',
  'now',
  'yes',
  'on',
  'for',
  'a',
  'bit',
  'of',
  'a',
  'run',
  'forgot',
  'that',
  'i',
  'have',
  'hairdresser',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'n',
  'shower',
  'beforehand',
  'doe',
  'that',
  'cause',
  'prob',
  'for',
  'u'],
 ['i', 'see', 'a', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'don',
  't',
  'text',
  'me',
  'anymore',
  'i',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'a',
  'long',
  'a',
  'it',
  'legal',
  'wen',
  'can',
  'i',
  'pick',
  'them',
  'up',
  'y',
  'u',
  'ave',
  'x',
  'am',
  'xx'],
 ['i',
  'm',
  'still',
  'looking',
  'for',
  'a',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  'the',
  'driving',
  'test',
  'yet'],
 ['a',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'a',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['wow',
  'you',
  're',
  'right',
  'i',
  'didn',
  't',
  'mean',
  'to',
  'do',
  'that',
  'i',
  'guess',
  'once',
  'i',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'changed',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'changed',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thanks',
  'a',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thanks',
  'you',
  'for',
  'making',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'i', 'll', 'hit', 'you', 'up', 'when', 'i', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'considering',
  'my',
  'computer',
  'isn',
  't',
  'a',
  'minecraft',
  'server'],
 ['i',
  'know',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'wa',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lying',
  'then',
  'again',
  'i',
  'am',
  'always',
  'the',
  'one',
  'to',
  'play',
  'joke'],
 ['dont', 'worry', 'i', 'guess', 'he', 's', 'busy'],
 ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['going', 'for', 'dinner', 'msg', 'you', 'after'],
 ['i',
  'm',
  'ok',
  'wif',
  'it',
  'co',
  'i',
  'like',
  'try',
  'new',
  'thing',
  'but',
  'i',
  'scared',
  'u',
  'dun',
  'like',
  'mah',
  'co',
  'u',
  'said',
  'not',
  'too',
  'loud'],
 ['gent',
  'we',
  'are',
  'trying',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'won',
  'a',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'k',
  'valid',
  'hr',
  'only',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'very',
  'formal',
  'anyway',
  'i',
  'm',
  'fine',
  'too',
  'juz',
  'tt',
  'i',
  'm',
  'eatin',
  'too',
  'much',
  'n',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happened'],
 ['a',
  'i',
  'entered',
  'my',
  'cabin',
  'my',
  'pa',
  'said',
  'happy',
  'b',
  'day',
  'bos',
  'i',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invited',
  'me',
  'to',
  'her',
  'apartment',
  'we',
  'went',
  'there'],
 ['you',
  'are',
  'a',
  'winner',
  'u',
  'have',
  'been',
  'specially',
  'selected',
  'receive',
  'or',
  'a',
  'holiday',
  'flight',
  'inc',
  'speak',
  'to',
  'a',
  'live',
  'operator',
  'claim',
  'p',
  'min'],
 ['goodo',
  'yes',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'needed'],
 ['hmm',
  'my',
  'uncle',
  'just',
  'informed',
  'me',
  'that',
  'he',
  's',
  'paying',
  'the',
  'school',
  'directly',
  'so',
  'pls',
  'buy',
  'food'],
 ['private',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'to',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['urgent',
  'your',
  'mobile',
  'no',
  'wa',
  'awarded',
  'bonus',
  'caller',
  'prize',
  'on',
  'this',
  'is',
  'our',
  'final',
  'try',
  'to',
  'contact',
  'u',
  'call',
  'from',
  'landline',
  'box',
  'wr',
  'c',

In [34]:
from nltk import word_tokenize,sent_tokenize

In [35]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
words = []
for sent in corpus:
    # If sent is a list, join it first
    if isinstance(sent, list):
        sent = ' '.join(sent)
    sent_token = sent_tokenize(sent)
    for s in sent_token:
        words.append(simple_preprocess(s))

In [36]:
import gensim

In [37]:
from gensim.models import Word2Vec

word2vec=Word2Vec(words,vector_size=100)

In [38]:
word2vec

In [39]:
# to get all the vocabulary

word2vec.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope',
 'oh',
 'claim',
 'great',
 'hey',
 'him',
 'number',
 'give',
 'more',
 'too',
 'happy',
 'work',
 'friend',
 'wat',
 'had',
 'way',
 'yes',
 'www',
 've',
 'should',
 'let',
 'prize',
 'won',
 'right',
 'tomorrow',
 'already',
 'tone',
 'after',
 'said',
 'ask',
 'win',
 'doing',
 'amp',
 'cash',
 'life',
 'im',
 'yeah',
 'really',
 'babe',
 'why',
 'meet',
 'find',
 'them',
 'miss',
 'very',
 'morning',
 'last',
 'service',
 'year',
 'uk',
 'thanks',
 'care',
 'would',
 'anything',
 'com',
 'also',
 'nokia',
 'lol',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',
 'over',
 'something',
 'gud',
 'buy',
 'again',
 'before',
 'cant',
 'wait',
 'box',
 'place',
 'first',
 'his',
 'even',
 'guy',
 'someone',
 'help',
 'went',
 'wish',
 'nice',
 'were',
 'next',
 'tonight',
 'off',
 'show',
 'which',
 'soon',
 'word',
 'around',
 'money',
 'could',
 'customer',
 'many',
 'sleep',
 'chat',
 'late',
 'per',
 'ya',
 'sm',
 'always',
 'gonna',
 'wan',
 'leave',
 'down',
 'name',
 'lot',
 'other',
 'pm',
 'end',
 'dun',
 'told',
 'st',
 'person',
 'waiting',
 'special',
 'hello',
 'girl',
 'try',
 'fine',
 'month',
 'hour',
 'may',
 'minute',
 'coming',
 'heart',
 'haha',
 'people',
 'best',
 'th',
 'thk',
 'yet',
 'guaranteed',
 'smile',
 'same',
 'done',
 'getting',
 'god',
 'ppm',
 'thought',
 'use',
 'offer',
 'didn',
 'start',
 'holiday',
 'class',
 'stuff',
 'talk',
 'line',
 'mean',
 'bit',
 'man',
 'live',
 'car',
 'lunch',
 'cost',
 'few',
 'draw',
 'job',
 'finish',
 'problem',
 'never',
 'being',
 'plan',
 'ill',
 'house',
 'hr',
 'better',
 'cool',
 'thats',
 'meeting',
 'trying',
 'yup',
 'mind',
 'having',
 'ready',
 'dat',
 'account',
 'long',
 'pobox',
 'rate',
 'game',
 'weekend',
 'chance',
 'enjoy',
 'wk',
 'real',
 'half',
 'latest',
 'than',
 'because',
 'world',
 'sir',
 'bt',
 'guess',
 'po',
 'yo',
 'check',
 'play',
 'room',
 'pic',
 'voucher',
 'boy',
 'luv',
 'nothing',
 'wanna',
 'awarded',
 'sweet',
 'look',
 'eat',
 'camera',
 'receive',
 'lar',
 'shit',
 'big',
 'liao',
 'another',
 'into',
 'landline',
 'birthday',
 'ah',
 'dinner',
 'xxx',
 'quite',
 'ever',
 'kiss',
 'might',
 'video',
 'jus',
 'age',
 'land',
 'watch',
 'watching',
 'wont',
 'question',
 'probably',
 'orange',
 'two',
 'baby',
 'thanx',
 'called',
 'tv',
 'dream',
 'worry',
 'aight',
 'bed',
 'pa',
 'once',
 'hear',
 'nd',
 'speak',
 'fun',
 'early',
 'princess',
 'bad',
 'den',
 'actually',
 'sat',
 'shall',
 'nite',
 'point',
 'forgot',
 'part',
 'maybe',
 'ringtone',
 'doe',
 'left',
 'bus',
 'pay',
 'remember',
 'network',
 'apply',
 'office',
 'dunno',
 'made',
 'shopping',
 'reach',
 'easy',
 'between',
 'hurt',
 'code',
 'dad',
 'wife',
 'fuck',
 'put',
 'true',
 'didnt',
 'everything',
 'face',
 'leh',
 'evening',
 'little',
 'award',
 'anyway',
 'xx',
 'dis',
 'mate',
 'town',
 'gift',
 'sound',
 'working',
 'those',
 'mail',
 'yr',
 'school',
 'movie',
 'afternoon',
 'looking',
 'thank',
 'enough',
 'selected',
 'while',
 'detail',
 'asked',
 'collect',
 'tmr',
 'missing',
 'without',
 'most',
 'pound',
 'entry',
 'important',
 'hav',
 'xmas',
 'sexy',
 'join',
 'must',
 'price',
 'okay',
 'came',
 'pain',
 'since',
 'wanted',
 'valid',
 'though',
 'wif',
 'collection',
 'bring',
 'wot',
 'book',
 'wake',
 'able',
 'til',
 'answer',
 'abt',
 'mob',
 'run',
 'missed',
 'lesson',
 'until',
 'update',
 'plus',
 'away',
 'de',
 'change',
 'plz',
 'charge',
 'decimal',
 'stay',
 'juz',
 'test',
 'haven',
 'wen',
 'date',
 'colour',
 'attempt',
 'bored',
 'dude',
 'weekly',
 'music',
 'shop',
 'else',
 'havent',
 'hair',
 'double',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'online',
 'these',
 'drink',
 'friendship',
 'optout',
 'oso',
 'id',
 'coz',
 'haf',
 'top',
 'food',
 'making',
 'trip',
 'yours',
 'credit',
 'net',
 'family',
 'sch',
 'either',
 'feeling',
 'club',
 'hot',
 'gr',
 'smoke',
 'player',
 'address',
 'driving',
 'yourself',
 'delivery',
 'tried',
 'ard',
 'national',
 'sad',
 'together',
 'lose',
 'sae',
 'beautiful',
 'tot',
 'head',
 'post',
 'calling',
 'full',
 'ring',
 'wid',
 'walk',
 'both',
 'story',
 'si',
 'believe',
 'order',
 'nt',
 'busy',
 'bonus',
 'second',
 'mom',
 'http',
 'brother',
 'await',
 'drive',
 'saying',
 'mum',
 'eve',
 'poly',
 'huh',
 'chikku',
 'row',
 'happen',
 'noe',
 'sleeping',
 'hand',
 'leaving',
 'old',
 'smiling',
 'close',
 'info',
 'set',
 'drop',
 'rite',
 'email',
 'pub',
 'simple',
 'thinking',
 'suite',
 'mths',
 'okie',
 'wil',
 'awesome',
 'parent',
 'match',
 'private',
 'cause',
 'started',
 'finished',
 'took',
 'congrats',
 'tomo',
 'doesn',
 'aft',
 'news',
 'hl',
 'auction',
 'anyone',
 'neva',
 'mine',
 'gd',
 'reason',
 'valentine',
 'sister',
 'card',
 'unsubscribe',
 'angry',
 'company',
 'tc',
 'break',
 'touch',
 'content',
 'everyone',
 'taking',
 'statement',
 'forget',
 'tho',
 'caller',
 'final',
 'alone',
 'loving',
 'gal',
 'knw',
 'sun',
 'whatever',
 'opt',
 'dating',
 'choose',
 'available',
 'found',
 'worth',
 'carlos',
 'bank',
 'fancy',
 'each',
 'whats',
 'open',
 'type',
 'expires',
 'search',
 'ticket',
 'lucky',
 'treat',
 'hows',
 'party',
 'fast',
 'sub',
 'visit',
 'nyt',
 'kind',
 'welcome',
 'bout',
 'mobileupd',
 'far',
 'anytime',
 'congratulation',
 'secret',
 'gbp',
 'exam',
 'college',
 'boytoy',
 'frnd',
 'hard',
 'ltd',
 'ni',
 'quiz',
 'identifier',
 'uncle',
 'friday',
 'happened',
 'hit',
 'gone',
 'prob',
 'song',
 'decided',
 'saturday',
 'smth',
 'wonderful',
 'winner',
 'chennai',
 'least',
 'wrong',
 'lovely',
 'wonder',
 'drug',
 'sea',
 'pretty',
 'fri',
 'outside',
 'nope',
 'term',
 'fucking',
 'project',
 'light',
 'read',
 'hold',
 'tel',
 'oredi',
 'goodmorning',
 'darlin',
 'mrng',
 'finally',
 'wit',
 'mu',
 'operator',
 'used',
 'camcorder',
 'wasn',
 'support',
 'crazy',
 'earlier',
 'snow',
 'listen',
 'savamob',
 'frm',
 'cum',
 'ten',
 'jay',
 'fone',
 'blue',
 'unlimited',
 'cd',
 'fr',
 'meant',
 'case',
 'course',
 'log',
 'their',
 'hmm',
 'isn',
 'frnds',
 'whole',
 'telling',
 'seeing',
 'hungry',
 'wq',
 'sunday',
 'freemsg',
 'wkly',
 'father',
 'gas',
 'john',
 'enter',
 'luck',
 'film',
 'na',
 'gn',
 'knew',
 'understand',
 'store',
 'mayb',
 'sell',
 'sex',
 'paper',
 'area',
 'happiness',
 'yar',
 'un',
 'within',
 'park',
 'sk',
 'india',
 'as',
 'rock',
 'couple',
 'talking',
 'motorola',
 'moment',
 'currently',
 'ago',
 'txts',
 'reading',
 'christmas',
 'lost',
 'bslvyl',
 'die',
 'stupid',
 'single',
 'dnt',
 'side',
 'march',
 'balance',
 'mr',
 'hmmm',
 'joy',
 'tired',
 'invited',
 'felt',
 'mah',
 'computer',
 'load',
 'download',
 'hee',
 'cut',
 'move',
 'etc',
 'pas',
 'almost',
 'child',
 'eh',
 'valued',
 'press',
 'difficult',
 'grin',
 'surprise',
 'information',
 'heard',
 'photo',
 'sort',
 'extra',
 'ugh',
 'picking',
 'eye',
 'xy',
 'darren',
 'kid',
 'gym',
 'through',
 'max',
 'redeemed',
 'lady',
 'ipod',
 'doin',
 'supposed',
 'rental',
 'seen',
 'met',
 'ish',
 'figure',
 'via',
 'return',
 'ge',
 'swing',
 'laptop',
 'reveal',
 'bcoz',
 'semester',
 'bill',
 'direct',
 'sending',
 'askd',
 'shower',
 'gotta',
 'complimentary',
 'correct',
 'red',
 'ac',
 'wow',
 'hospital',
 'confirm',
 'charged',
 'promise',
 'comp',
 'police',
 'slowly',
 'loved',
 'fact',
 'fantasy',
 'nobody',
 'truth',
 'asap',
 'whenever',
 'idea',
 'laugh',
 'noon',
 'train',
 'door',
 'clean',
 'blood',
 'member',
 'rent',
 'monday',
 'remove',
 'asking',
 'yep',
 'slow',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'pete',
 'rest',
 'somebody',
 'hmv',
 'leaf',
 'wana',
 'own',
 'lover',
 'road',
 'study',
 'kate',
 'orchard',
 'bath',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'dogging',
 'entered',
 'page',
 'loan',
 'save',
 'rply',
 'checking',
 'joke',
 'crave',
 'abiola',
 'cheer',
 'comin',
 'eg',
 'link',
 'wap',
 'reward',
 'request',
 'usf',
 'std',
 'empty',
 'med',
 'hw',
 'cover',
 'write',
 'bb',
 'ringtones',
 'energy',
 'doctor',
 'convey',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwise',
 'poor',
 'gettin',
 'bag',
 'getzed',
 'summer',
 'wishing',
 'glad',
 'fantastic',
 'gap',
 'king',
 'ho',
 'indian',
 'em',
 'cheap',
 'warm',
 'across',
 'hoping',
 'less',
 'opinion',
 'near',
 'water',
 'different',
 'booked',
 'wc',
 'ldn',
 'voice',
 'mm',
 'mistake',
 'woke',
 'rakhesh',
 'custcare',
 'immediately',
 'merry',
 'normal',
 'somewhere',
 'tonite',
 'usual',
 'deep',
 'admirer',
 'kick',
 'street',
 'teach',
 'deal',
 'bathe',
 'spend',
 'pray',
 'sony',
 'del',
 'men',
 'gave',
 'representative',
 'il',
 'short',
 'forever',
 'situation',
 'reached',
 'oops',
 'catch',
 'turn',
 ...]

In [40]:
word2vec.epochs

5

In [41]:
word2vec.wv.similar_by_word('kid')

[('even', 0.9970206618309021),
 ('into', 0.9969488978385925),
 ('fine', 0.996807873249054),
 ('over', 0.9967664480209351),
 ('were', 0.996753990650177),
 ('down', 0.9967353343963623),
 ('smile', 0.9967345595359802),
 ('gonna', 0.9966759085655212),
 ('without', 0.9966741800308228),
 ('bring', 0.9966621994972229)]

In [42]:
word2vec.wv['good']

array([-0.2944069 ,  0.46802106,  0.15463871,  0.055502  ,  0.12957838,
       -0.77729714,  0.2509151 ,  0.74805456, -0.32608473, -0.18168561,
       -0.2634288 , -0.6193322 , -0.08707095,  0.09257574,  0.35481304,
       -0.3181264 ,  0.1666385 , -0.35845208, -0.1463867 , -0.7633603 ,
        0.46346408,  0.291355  ,  0.20182033, -0.23391622, -0.11092345,
        0.13013552, -0.4454612 , -0.50214547, -0.37672698,  0.1513783 ,
        0.4544661 ,  0.03433774,  0.23240381, -0.39846787, -0.19406483,
        0.4929813 ,  0.00702644, -0.23563619, -0.1998264 , -0.59684217,
        0.08078638, -0.3738609 , -0.18540476,  0.09253069,  0.38744518,
       -0.03512761, -0.2969086 , -0.1469098 ,  0.12475637,  0.34943658,
        0.1844642 , -0.32748783, -0.19782597, -0.08440175, -0.06977014,
        0.1853277 ,  0.19491203,  0.06698538, -0.4387112 ,  0.17335795,
        0.02046712,  0.09856437, -0.10336886, -0.17033009, -0.4324131 ,
        0.44357026,  0.16377458,  0.32385203, -0.48686165,  0.49691367,
       -0.222931  ,  0.10386036,  0.4517793 , -0.20610835,  0.39884052,
        0.19959861,  0.06969514, -0.11221416, -0.26455534,  0.11220358,
       -0.2817018 ,  0.0388871 , -0.25473326,  0.45585182, -0.22334972,
        0.03149812,  0.1733186 ,  0.37759066,  0.48712492, -0.03559386,
        0.47789896,  0.19079998,  0.10692094,  0.02748983,  0.61798924,
        0.4262273 ,  0.14259395, -0.2880328 ,  0.13259138, -0.10728048],
      dtype=float32)

In [43]:
word2vec.wv['good'].shape # as we kept the vector size=100

(100,)

In [44]:
words[0]

['ok', 'lar', 'joking', 'wif', 'oni']

In [45]:
word2vec.wv['ok'] # will give 100 dimensions

array([-0.25281343,  0.42380643,  0.13991112,  0.04442045,  0.1290727 ,
       -0.7423748 ,  0.22456537,  0.6913518 , -0.29338297, -0.15565401,
       -0.23634832, -0.53979766, -0.13540603,  0.07085937,  0.34008798,
       -0.29900235,  0.15149729, -0.35279888, -0.12729707, -0.7071675 ,
        0.39301103,  0.23910446,  0.18365395, -0.21274899, -0.12197653,
        0.11546952, -0.4474314 , -0.49681613, -0.35402676,  0.14424413,
        0.4442415 ,  0.03424821,  0.22150633, -0.36673695, -0.17517114,
        0.43152982,  0.00220315, -0.2244749 , -0.20322797, -0.57547367,
        0.08748771, -0.3455716 , -0.18598126,  0.06566314,  0.37537578,
       -0.05120821, -0.2826438 , -0.10832729,  0.15048274,  0.3568922 ,
        0.13614279, -0.29211202, -0.17402676, -0.02822032, -0.11608067,
        0.19186628,  0.18279554,  0.07406207, -0.41412207,  0.19355181,
        0.05468173,  0.11778706, -0.07769735, -0.13912757, -0.37833127,
        0.44526005,  0.14616387,  0.29859486, -0.48707598,  0.46040025,
       -0.23043437,  0.13708477,  0.40383226, -0.22584563,  0.40706545,
        0.19148272,  0.02301144, -0.0760785 , -0.2667713 ,  0.08692121,
       -0.25319007,  0.02959545, -0.27034533,  0.45833474, -0.22915134,
        0.03668112,  0.18388544,  0.3669116 ,  0.42691913, -0.05954265,
        0.4324636 ,  0.18946058,  0.08905589,  0.02359187,  0.5698628 ,
        0.36237   ,  0.10094637, -0.29766187,  0.1080478 , -0.0895312 ],
      dtype=float32)

so now each words present in the sentence for them 100 dimension vectors are created...so for it we use average vector

which basically calculates average of each word
```
['ok', 'lar', 'joking', 'wif', 'u', 'oni']

ok              lar         joking                   average word2vec
|                |            |        ........    
0.23           0.89          0.23                    avearge of 0.23,0.89,0.23 andd .....
0.45           .              .                      avearge of 0.45 andd ..... 
.              .              .
.               .             .
.
100 vectors  100 vectors  100 vectors```

In [46]:
words[0]

['ok', 'lar', 'joking', 'wif', 'oni']

In [47]:
word2vec.wv['ok']

array([-0.25281343,  0.42380643,  0.13991112,  0.04442045,  0.1290727 ,
       -0.7423748 ,  0.22456537,  0.6913518 , -0.29338297, -0.15565401,
       -0.23634832, -0.53979766, -0.13540603,  0.07085937,  0.34008798,
       -0.29900235,  0.15149729, -0.35279888, -0.12729707, -0.7071675 ,
        0.39301103,  0.23910446,  0.18365395, -0.21274899, -0.12197653,
        0.11546952, -0.4474314 , -0.49681613, -0.35402676,  0.14424413,
        0.4442415 ,  0.03424821,  0.22150633, -0.36673695, -0.17517114,
        0.43152982,  0.00220315, -0.2244749 , -0.20322797, -0.57547367,
        0.08748771, -0.3455716 , -0.18598126,  0.06566314,  0.37537578,
       -0.05120821, -0.2826438 , -0.10832729,  0.15048274,  0.3568922 ,
        0.13614279, -0.29211202, -0.17402676, -0.02822032, -0.11608067,
        0.19186628,  0.18279554,  0.07406207, -0.41412207,  0.19355181,
        0.05468173,  0.11778706, -0.07769735, -0.13912757, -0.37833127,
        0.44526005,  0.14616387,  0.29859486, -0.48707598,  0.46040025,
       -0.23043437,  0.13708477,  0.40383226, -0.22584563,  0.40706545,
        0.19148272,  0.02301144, -0.0760785 , -0.2667713 ,  0.08692121,
       -0.25319007,  0.02959545, -0.27034533,  0.45833474, -0.22915134,
        0.03668112,  0.18388544,  0.3669116 ,  0.42691913, -0.05954265,
        0.4324636 ,  0.18946058,  0.08905589,  0.02359187,  0.5698628 ,
        0.36237   ,  0.10094637, -0.29766187,  0.1080478 , -0.0895312 ],
      dtype=float32)

In [48]:
word2vec.wv[words[0][0]]

array([-0.25281343,  0.42380643,  0.13991112,  0.04442045,  0.1290727 ,
       -0.7423748 ,  0.22456537,  0.6913518 , -0.29338297, -0.15565401,
       -0.23634832, -0.53979766, -0.13540603,  0.07085937,  0.34008798,
       -0.29900235,  0.15149729, -0.35279888, -0.12729707, -0.7071675 ,
        0.39301103,  0.23910446,  0.18365395, -0.21274899, -0.12197653,
        0.11546952, -0.4474314 , -0.49681613, -0.35402676,  0.14424413,
        0.4442415 ,  0.03424821,  0.22150633, -0.36673695, -0.17517114,
        0.43152982,  0.00220315, -0.2244749 , -0.20322797, -0.57547367,
        0.08748771, -0.3455716 , -0.18598126,  0.06566314,  0.37537578,
       -0.05120821, -0.2826438 , -0.10832729,  0.15048274,  0.3568922 ,
        0.13614279, -0.29211202, -0.17402676, -0.02822032, -0.11608067,
        0.19186628,  0.18279554,  0.07406207, -0.41412207,  0.19355181,
        0.05468173,  0.11778706, -0.07769735, -0.13912757, -0.37833127,
        0.44526005,  0.14616387,  0.29859486, -0.48707598,  0.46040025,
       -0.23043437,  0.13708477,  0.40383226, -0.22584563,  0.40706545,
        0.19148272,  0.02301144, -0.0760785 , -0.2667713 ,  0.08692121,
       -0.25319007,  0.02959545, -0.27034533,  0.45833474, -0.22915134,
        0.03668112,  0.18388544,  0.3669116 ,  0.42691913, -0.05954265,
        0.4324636 ,  0.18946058,  0.08905589,  0.02359187,  0.5698628 ,
        0.36237   ,  0.10094637, -0.29766187,  0.1080478 , -0.0895312 ],
      dtype=float32)

In [49]:
import numpy as np

In [50]:
def avg_wrod2vec(doc):
    vectors = [word2vec.wv[word] for word in doc if word in word2vec.wv.index_to_key]
    if len(vectors) == 0:
        return np.zeros(word2vec.vector_size)  # empty message handle
    return np.mean(vectors, axis=0)

In [51]:
pip install tqdm

Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (4.67.1)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from tqdm) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [52]:
from tqdm import tqdm

In [53]:
X=[]
for i in tqdm(range(len(words))):
    print("hello",i)
    X.append(avg_wrod2vec(words[i]))

  7%|▋         | 377/5568 [00:00<00:01, 3750.03it/s]

hello 0
hello 1
hello 2
hello 3
hello 4
hello 5
hello 6
hello 7
hello 8
hello 9
hello 10
hello 11
hello 12
hello 13
hello 14
hello 15
hello 16
hello 17
hello 18
hello 19
hello 20
hello 21
hello 22
hello 23
hello 24
hello 25
hello 26
hello 27
hello 28
hello 29
hello 30
hello 31
hello 32
hello 33
hello 34
hello 35
hello 36
hello 37
hello 38
hello 39
hello 40
hello 41
hello 42
hello 43
hello 44
hello 45
hello 46
hello 47
hello 48
hello 49
hello 50
hello 51
hello 52
hello 53
hello 54
hello 55
hello 56
hello 57
hello 58
hello 59
hello 60
hello 61
hello 62
hello 63
hello 64
hello 65
hello 66
hello 67
hello 68
hello 69
hello 70
hello 71
hello 72
hello 73
hello 74
hello 75
hello 76
hello 77
hello 78
hello 79
hello 80
hello 81
hello 82
hello 83
hello 84
hello 85
hello 86
hello 87
hello 88
hello 89
hello 90
hello 91
hello 92
hello 93
hello 94
hello 95
hello 96
hello 97
hello 98
hello 99
hello 100
hello 101
hello 102
hello 103
hello 104
hello 105
hello 106
hello 107
hello 108
hello 109
hello 110
hello 111
hello 112
hello 113
hello 114
hello 115
hello 116
hello 117
hello 118
hello 119
hello 120
hello 121
hello 122
hello 123
hello 124
hello 125
hello 126
hello 127
hello 128
hello 129
hello 130
hello 131
hello 132
hello 133
hello 134
hello 135
hello 136
hello 137
hello 138
hello 139
hello 140
hello 141
hello 142
hello 143
hello 144
hello 145
hello 146
hello 147
hello 148
hello 149
hello 150
hello 151
hello 152
hello 153
hello 154
hello 155
hello 156
hello 157
hello 158
hello 159
hello 160
hello 161
hello 162
hello 163
hello 164
hello 165
hello 166
hello 167
hello 168
hello 169
hello 170
hello 171
hello 172
hello 173
hello 174
hello 175
hello 176
hello 177
hello 178
hello 179
hello 180
hello 181
hello 182
hello 183
hello 184
hello 185
hello 186
hello 187
hello 188
hello 189
hello 190
hello 191
hello 192
hello 193
hello 194
hello 195
hello 196
hello 197
hello 198
hello 199
hello 200
hello 201
hello 202
hello 203
hello 204
hello 205
hello 206
hello 207
hello 208
hello 209
hello 210
hello 211
hello 212
hello 213
hello 214
hello 215
hello 216
hello 217
hello 218
hello 219
hello 220
hello 221
hello 222
hello 223
hello 224
hello 225
hello 226
hello 227
hello 228
hello 229
hello 230
hello 231
hello 232
hello 233
hello 234
hello 235
hello 236
hello 237
hello 238
hello 239
hello 240
hello 241
hello 242
hello 243
hello 244
hello 245
hello 246
hello 247
hello 248
hello 249
hello 250
hello 251
hello 252
hello 253
hello 254
hello 255
hello 256
hello 257
hello 258
hello 259
hello 260
hello 261
hello 262
hello 263
hello 264
hello 265
hello 266
hello 267
hello 268
hello 269
hello 270
hello 271
hello 272
hello 273
hello 274
hello 275
hello 276
hello 277
hello 278
hello 279
hello 280
hello 281
hello 282
hello 283
hello 284
hello 285
hello 286
hello 287
hello 288
hello 289
hello 290
hello 291
hello 292
hello 293
hello 294
hello 295
hello 296
hello 297
hello 298
hello 299
hello 300
hello 301
hello 302
hello 303
hello 304
hello 305
hello 306
hello 307
hello 308
hello 309
hello 310
hello 311
hello 312
hello 313
hello 314
hello 315
hello 316
hello 317
hello 318
hello 319
hello 320
hello 321
hello 322
hello 323
hello 324
hello 325
hello 326
hello 327
hello 328
hello 329
hello 330
hello 331
hello 332
hello 333
hello 334
hello 335
hello 336
hello 337
hello 338
hello 339
hello 340
hello 341
hello 342
hello 343
hello 344
hello 345
hello 346
hello 347
hello 348
hello 349
hello 350
hello 351
hello 352
hello 353
hello 354
hello 355
hello 356
hello 357
hello 358
hello 359
hello 360
hello 361
hello 362
hello 363
hello 364
hello 365
hello 366
hello 367
hello 368
hello 369
hello 370
hello 371
hello 372
hello 373
hello 374
hello 375
hello 376
hello 377
hello 378
hello 379
hello 380
hello 381
hello 382
hello 383
hello 384
hello 385
hello 386
hello 387
hello 388
hello 389
hello 390
hello 391
hello 392
hello 393
hello 394
hello 395
hello 396
hello 397
hello 398
hello 399
hello 400
hello 401
hello 402
hello 403
hello 404
hello 405
hello 406
hello 407
hello 408
hello 409
hello 410
hello 411
hello 412
hello 413
hello 414
hello 415
hello 416
hello 417
hello 418
hello 419
hello 420
hello 421
hello 422
hello 423
hello 424
hello 425
hello 426
hello 427
hello 428
hello 429
hello 430
hello 431
hello 432
hello 433
hello 434
hello 435
hello 436
hello 437
hello 438
hello 439
hello 440
hello 441
hello 442
hello 443
hello 444
hello 445
hello 446
hello 447
hello 448
hello 449
hello 450
hello 451
hello 452
hello 453
hello 454
hello 455
hello 456
hello 457
hello 458
hello 459
hello 460
hello 461
hello 462
hello 463
hello 464
hello 465
hello 466
hello 467
hello 468
hello 469
hello 470
hello 471
hello 472
hello 473
hello 474
hello 475
hello 476
hello 477
hello 478
hello 479
hello 480
hello 481
hello 482
hello 483
hello 484
hello 485
hello 486
hello 487
hello 488
hello 489
hello 490
hello 491
hello 492
hello 493
hello 494
hello 495
hello 496
hello 497
hello 498
hello 499
hello 500
hello 501
hello 502
hello 503
hello 504
hello 505
hello 506
hello 507
hello 508
hello 509
hello 510
hello 511
hello 512
hello 513
hello 514
hello 515
hello 516
hello 517
hello 518
hello 519
hello 520
hello 521
hello 522
hello 523
hello 524
hello 525
hello 526
hello 527
hello 528
hello 529
hello 530
hello 531
hello 532
hello 533
hello 534
hello 535
hello 536
hello 537
hello 538
hello 539
hello 540
hello 541
hello 542
hello 543
hello 544
hello 545
hello 546
hello 547
hello 548
hello 549
hello 550
hello 551
hello 552
hello 553
hello 554
hello 555
hello 556
hello 557
hello 558
hello 559
hello 560
hello 561
hello 562
hello 563
hello 564
hello 565
hello 566
hello 567
hello 568
hello 569
hello 570
hello 571
hello 572
hello 573
hello 574
hello 575
hello 576
hello 577
hello 578
hello 579
hello 580
hello 581
hello 582
hello 583
hello 584
hello 585
hello 586
hello 587
hello 588
hello 589
hello 590
hello 591
hello 592
hello 593
hello 594
hello 595
hello 596
hello 597
hello 598
hello 599
hello 600
hello 601
hello 602
hello 603
hello 604
hello 605
hello 606
hello 607
hello 608
hello 609
hello 610
hello 611
hello 612
hello 613
hello 614
hello 615
hello 616
hello 617
hello 618
hello 619
hello 620
hello 621
hello 622
hello 623
hello 624
hello 625
hello 626
hello 627
hello 628
hello 629
hello 630
hello 631
hello 632
hello 633
hello 634
hello 635
hello 636
hello 637
hello 638
hello 639
hello 640
hello 641
hello 642
hello 643
hello 644
hello 645
hello 646
hello 647
hello 648
hello 649
hello 650
hello 651
hello 652
hello 653
hello 654
hello 655
hello 656
hello 657
hello 658
hello 659
hello 660
hello 661
hello 662
hello 663
hello 664
hello 665
hello 666
hello 667
hello 668
hello 669
hello 670
hello 671
hello 672
hello 673
hello 674
hello 675
hello 676
hello 677
hello 678
hello 679
hello 680
hello 681
hello 682
hello 683
hello 684
hello 685
hello 686
hello 687
hello 688
hello 689
hello 690
hello 691
hello 692
hello 693
hello 694
hello 695
hello 696
hello 697
hello 698
hello 699
hello 700
hello 701
hello 702
hello 703
hello 704
hello 705
hello 706
hello 707
hello 708
hello 709
hello 710
hello 711
hello 712
hello 713
hello 714
hello 715
hello 716
hello 717
hello 718
hello 719
hello 720
hello 721
hello 722
hello 723
hello 724
hello 725
hello 726
hello 727
hello 728
hello 729
hello 730
hello 731
hello 732
hello 733
hello 734

 25%|██▌       | 1406/5568 [00:00<00:00, 4765.74it/s]

hello 735
hello 736
hello 737
hello 738
hello 739
hello 740
hello 741
hello 742
hello 743
hello 744
hello 745
hello 746
hello 747
hello 748
hello 749
hello 750
hello 751
hello 752
hello 753
hello 754
hello 755
hello 756
hello 757
hello 758
hello 759
hello 760
hello 761
hello 762
hello 763
hello 764
hello 765
hello 766
hello 767
hello 768
hello 769
hello 770
hello 771
hello 772
hello 773
hello 774
hello 775
hello 776
hello 777
hello 778
hello 779
hello 780
hello 781
hello 782
hello 783
hello 784
hello 785
hello 786
hello 787
hello 788
hello 789
hello 790
hello 791
hello 792
hello 793
hello 794
hello 795
hello 796
hello 797
hello 798
hello 799
hello 800
hello 801
hello 802
hello 803
hello 804
hello 805
hello 806
hello 807
hello 808
hello 809
hello 810
hello 811
hello 812
hello 813
hello 814
hello 815
hello 816
hello 817
hello 818
hello 819
hello 820
hello 821
hello 822
hello 823
hello 824
hello 825
hello 826
hello 827
hello 828
hello 829
hello 830
hello 831
hello 832
hello 833
hello 834
hello 835
hello 836
hello 837
hello 838
hello 839
hello 840
hello 841
hello 842
hello 843
hello 844
hello 845
hello 846
hello 847
hello 848
hello 849
hello 850
hello 851
hello 852
hello 853
hello 854
hello 855
hello 856
hello 857
hello 858
hello 859
hello 860
hello 861
hello 862
hello 863
hello 864
hello 865
hello 866
hello 867
hello 868
hello 869
hello 870
hello 871
hello 872
hello 873
hello 874
hello 875
hello 876
hello 877
hello 878
hello 879
hello 880
hello 881
hello 882
hello 883
hello 884
hello 885
hello 886
hello 887
hello 888
hello 889
hello 890
hello 891
hello 892
hello 893
hello 894
hello 895
hello 896
hello 897
hello 898
hello 899
hello 900
hello 901
hello 902
hello 903
hello 904
hello 905
hello 906
hello 907
hello 908
hello 909
hello 910
hello 911
hello 912
hello 913
hello 914
hello 915
hello 916
hello 917
hello 918
hello 919
hello 920
hello 921
hello 922
hello 923
hello 924
hello 925
hello 926
hello 927
hello 928
hello 929
hello 930
hello 931
hello 932
hello 933
hello 934
hello 935
hello 936
hello 937
hello 938
hello 939
hello 940
hello 941
hello 942
hello 943
hello 944
hello 945
hello 946
hello 947
hello 948
hello 949
hello 950
hello 951
hello 952
hello 953
hello 954
hello 955
hello 956
hello 957
hello 958
hello 959
hello 960
hello 961
hello 962
hello 963
hello 964
hello 965
hello 966
hello 967
hello 968
hello 969
hello 970
hello 971
hello 972
hello 973
hello 974
hello 975
hello 976
hello 977
hello 978
hello 979
hello 980
hello 981
hello 982
hello 983
hello 984
hello 985
hello 986
hello 987
hello 988
hello 989
hello 990
hello 991
hello 992
hello 993
hello 994
hello 995
hello 996
hello 997
hello 998
hello 999
hello 1000
hello 1001
hello 1002
hello 1003
hello 1004
hello 1005
hello 1006
hello 1007
hello 1008
hello 1009
hello 1010
hello 1011
hello 1012
hello 1013
hello 1014
hello 1015
hello 1016
hello 1017
hello 1018
hello 1019
hello 1020
hello 1021
hello 1022
hello 1023
hello 1024
hello 1025
hello 1026
hello 1027
hello 1028
hello 1029
hello 1030
hello 1031
hello 1032
hello 1033
hello 1034
hello 1035
hello 1036
hello 1037
hello 1038
hello 1039
hello 1040
hello 1041
hello 1042
hello 1043
hello 1044
hello 1045
hello 1046
hello 1047
hello 1048
hello 1049
hello 1050
hello 1051
hello 1052
hello 1053
hello 1054
hello 1055
hello 1056
hello 1057
hello 1058
hello 1059
hello 1060
hello 1061
hello 1062
hello 1063
hello 1064
hello 1065
hello 1066
hello 1067
hello 1068
hello 1069
hello 1070
hello 1071
hello 1072
hello 1073
hello 1074
hello 1075
hello 1076
hello 1077
hello 1078
hello 1079
hello 1080
hello 1081
hello 1082
hello 1083
hello 1084
hello 1085
hello 1086
hello 1087
hello 1088
hello 1089
hello 1090
hello 1091
hello 1092
hello 1093
hello 1094
hello 1095
hello 1096
hello 1097
hello 1098
hello 1099
hello 1100
hello 1101
hello 1102
hello 1103
hello 1104
hello 1105
hello 1106
hello 1107
hello 1108
hello 1109
hello 1110
hello 1111
hello 1112
hello 1113
hello 1114
hello 1115
hello 1116
hello 1117
hello 1118
hello 1119
hello 1120
hello 1121
hello 1122
hello 1123
hello 1124
hello 1125
hello 1126
hello 1127
hello 1128
hello 1129
hello 1130
hello 1131
hello 1132
hello 1133
hello 1134
hello 1135
hello 1136
hello 1137
hello 1138
hello 1139
hello 1140
hello 1141
hello 1142
hello 1143
hello 1144
hello 1145
hello 1146
hello 1147
hello 1148
hello 1149
hello 1150
hello 1151
hello 1152
hello 1153
hello 1154
hello 1155
hello 1156
hello 1157
hello 1158
hello 1159
hello 1160
hello 1161
hello 1162
hello 1163
hello 1164
hello 1165
hello 1166
hello 1167
hello 1168
hello 1169
hello 1170
hello 1171
hello 1172
hello 1173
hello 1174
hello 1175
hello 1176
hello 1177
hello 1178
hello 1179
hello 1180
hello 1181
hello 1182
hello 1183
hello 1184
hello 1185
hello 1186
hello 1187
hello 1188
hello 1189
hello 1190
hello 1191
hello 1192
hello 1193
hello 1194
hello 1195
hello 1196
hello 1197
hello 1198
hello 1199
hello 1200
hello 1201
hello 1202
hello 1203
hello 1204
hello 1205
hello 1206
hello 1207
hello 1208
hello 1209
hello 1210
hello 1211
hello 1212
hello 1213
hello 1214
hello 1215
hello 1216
hello 1217
hello 1218
hello 1219
hello 1220
hello 1221
hello 1222
hello 1223
hello 1224
hello 1225
hello 1226
hello 1227
hello 1228
hello 1229
hello 1230
hello 1231
hello 1232
hello 1233
hello 1234
hello 1235
hello 1236
hello 1237
hello 1238
hello 1239
hello 1240
hello 1241
hello 1242
hello 1243
hello 1244
hello 1245
hello 1246
hello 1247
hello 1248
hello 1249
hello 1250
hello 1251
hello 1252
hello 1253
hello 1254
hello 1255
hello 1256
hello 1257
hello 1258
hello 1259
hello 1260
hello 1261
hello 1262
hello 1263
hello 1264
hello 1265
hello 1266
hello 1267
hello 1268
hello 1269
hello 1270
hello 1271
hello 1272
hello 1273
hello 1274
hello 1275
hello 1276
hello 1277
hello 1278
hello 1279
hello 1280
hello 1281
hello 1282
hello 1283
hello 1284
hello 1285
hello 1286
hello 1287
hello 1288
hello 1289
hello 1290
hello 1291
hello 1292
hello 1293
hello 1294
hello 1295
hello 1296
hello 1297
hello 1298
hello 1299
hello 1300
hello 1301
hello 1302
hello 1303
hello 1304
hello 1305
hello 1306
hello 1307
hello 1308
hello 1309
hello 1310
hello 1311
hello 1312
hello 1313
hello 1314
hello 1315
hello 1316
hello 1317
hello 1318
hello 1319
hello 1320
hello 1321
hello 1322
hello 1323
hello 1324
hello 1325
hello 1326
hello 1327
hello 1328
hello 1329
hello 1330
hello 1331
hello 1332
hello 1333
hello 1334
hello 1335
hello 1336
hello 1337
hello 1338
hello 1339
hello 1340
hello 1341
hello 1342
hello 1343
hello 1344
hello 1345
hello 1346
hello 1347
hello 1348
hello 1349
hello 1350
hello 1351
hello 1352
hello 1353
hello 1354
hello 1355
hello 1356
hello 1357
hello 1358
hello 1359
hello 1360
hello 1361
hello 1362
hello 1363
hello 1364
hello 1365
hello 1366
hello 1367
hello 1368
hello 1369
hello 1370
hello 1371
hello 1372
hello 1373
hello 1374
hello 1375
hello 1376
hello 1377
hello 1378
hello 1379
hello 1380
hello 1381
hello 1382
hello 1383
hello 1384
hello 1385
hello 1386
hello 1387
hello 1388
hello 1389
hello 1390
hello 1391
hello 1392
hello 1393
hello 1394
hello 1395
hello 1396
hello 1397
hello 1398
hello 1399
hello 1400
hello 1401
hello 1402
hello 1403
hello 1404
hello 1405

 34%|███▍      | 1885/5568 [00:00<00:00, 4767.11it/s]

hello 1406
hello 1407
hello 1408
hello 1409
hello 1410
hello 1411
hello 1412
hello 1413
hello 1414
hello 1415
hello 1416
hello 1417
hello 1418
hello 1419
hello 1420
hello 1421
hello 1422
hello 1423
hello 1424
hello 1425
hello 1426
hello 1427
hello 1428
hello 1429
hello 1430
hello 1431
hello 1432
hello 1433
hello 1434
hello 1435
hello 1436
hello 1437
hello 1438
hello 1439
hello 1440
hello 1441
hello 1442
hello 1443
hello 1444
hello 1445
hello 1446
hello 1447
hello 1448
hello 1449
hello 1450
hello 1451
hello 1452
hello 1453
hello 1454
hello 1455
hello 1456
hello 1457
hello 1458
hello 1459
hello 1460
hello 1461
hello 1462
hello 1463
hello 1464
hello 1465
hello 1466
hello 1467
hello 1468
hello 1469
hello 1470
hello 1471
hello 1472
hello 1473
hello 1474
hello 1475
hello 1476
hello 1477
hello 1478
hello 1479
hello 1480
hello 1481
hello 1482
hello 1483
hello 1484
hello 1485
hello 1486
hello 1487
hello 1488
hello 1489
hello 1490
hello 1491
hello 1492
hello 1493
hello 1494
hello 1495
hello 1496
hello 1497
hello 1498
hello 1499
hello 1500
hello 1501
hello 1502
hello 1503
hello 1504
hello 1505
hello 1506
hello 1507
hello 1508
hello 1509
hello 1510
hello 1511
hello 1512
hello 1513
hello 1514
hello 1515
hello 1516
hello 1517
hello 1518
hello 1519
hello 1520
hello 1521
hello 1522
hello 1523
hello 1524
hello 1525
hello 1526
hello 1527
hello 1528
hello 1529
hello 1530
hello 1531
hello 1532
hello 1533
hello 1534
hello 1535
hello 1536
hello 1537
hello 1538
hello 1539
hello 1540
hello 1541
hello 1542
hello 1543
hello 1544
hello 1545
hello 1546
hello 1547
hello 1548
hello 1549
hello 1550
hello 1551
hello 1552
hello 1553
hello 1554
hello 1555
hello 1556
hello 1557
hello 1558
hello 1559
hello 1560
hello 1561
hello 1562
hello 1563
hello 1564
hello 1565
hello 1566
hello 1567
hello 1568
hello 1569
hello 1570
hello 1571
hello 1572
hello 1573
hello 1574
hello 1575
hello 1576
hello 1577
hello 1578
hello 1579
hello 1580
hello 1581
hello 1582
hello 1583
hello 1584
hello 1585
hello 1586
hello 1587
hello 1588
hello 1589
hello 1590
hello 1591
hello 1592
hello 1593
hello 1594
hello 1595
hello 1596
hello 1597
hello 1598
hello 1599
hello 1600
hello 1601
hello 1602
hello 1603
hello 1604
hello 1605
hello 1606
hello 1607
hello 1608
hello 1609
hello 1610
hello 1611
hello 1612
hello 1613
hello 1614
hello 1615
hello 1616
hello 1617
hello 1618
hello 1619
hello 1620
hello 1621
hello 1622
hello 1623
hello 1624
hello 1625
hello 1626
hello 1627
hello 1628
hello 1629
hello 1630
hello 1631
hello 1632
hello 1633
hello 1634
hello 1635
hello 1636
hello 1637
hello 1638
hello 1639
hello 1640
hello 1641
hello 1642
hello 1643
hello 1644
hello 1645
hello 1646
hello 1647
hello 1648
hello 1649
hello 1650
hello 1651
hello 1652
hello 1653
hello 1654
hello 1655
hello 1656
hello 1657
hello 1658
hello 1659
hello 1660
hello 1661
hello 1662
hello 1663
hello 1664
hello 1665
hello 1666
hello 1667
hello 1668
hello 1669
hello 1670
hello 1671
hello 1672
hello 1673
hello 1674
hello 1675
hello 1676
hello 1677
hello 1678
hello 1679
hello 1680
hello 1681
hello 1682
hello 1683
hello 1684
hello 1685
hello 1686
hello 1687
hello 1688
hello 1689
hello 1690
hello 1691
hello 1692
hello 1693
hello 1694
hello 1695
hello 1696
hello 1697
hello 1698
hello 1699
hello 1700
hello 1701
hello 1702
hello 1703
hello 1704
hello 1705
hello 1706
hello 1707
hello 1708
hello 1709
hello 1710
hello 1711
hello 1712
hello 1713
hello 1714
hello 1715
hello 1716
hello 1717
hello 1718
hello 1719
hello 1720
hello 1721
hello 1722
hello 1723
hello 1724
hello 1725
hello 1726
hello 1727
hello 1728
hello 1729
hello 1730
hello 1731
hello 1732
hello 1733
hello 1734
hello 1735
hello 1736
hello 1737
hello 1738
hello 1739
hello 1740
hello 1741
hello 1742
hello 1743
hello 1744
hello 1745
hello 1746
hello 1747
hello 1748
hello 1749
hello 1750
hello 1751
hello 1752
hello 1753
hello 1754
hello 1755
hello 1756
hello 1757
hello 1758
hello 1759
hello 1760
hello 1761
hello 1762
hello 1763
hello 1764
hello 1765
hello 1766
hello 1767
hello 1768
hello 1769
hello 1770
hello 1771
hello 1772
hello 1773
hello 1774
hello 1775
hello 1776
hello 1777
hello 1778
hello 1779
hello 1780
hello 1781
hello 1782
hello 1783
hello 1784
hello 1785
hello 1786
hello 1787
hello 1788
hello 1789
hello 1790
hello 1791
hello 1792
hello 1793
hello 1794
hello 1795
hello 1796
hello 1797
hello 1798
hello 1799
hello 1800
hello 1801
hello 1802
hello 1803
hello 1804
hello 1805
hello 1806
hello 1807
hello 1808
hello 1809
hello 1810
hello 1811
hello 1812
hello 1813
hello 1814
hello 1815
hello 1816
hello 1817
hello 1818
hello 1819
hello 1820
hello 1821
hello 1822
hello 1823
hello 1824
hello 1825
hello 1826
hello 1827
hello 1828
hello 1829
hello 1830
hello 1831
hello 1832
hello 1833
hello 1834
hello 1835
hello 1836
hello 1837
hello 1838
hello 1839
hello 1840
hello 1841
hello 1842
hello 1843
hello 1844
hello 1845
hello 1846
hello 1847
hello 1848
hello 1849
hello 1850
hello 1851
hello 1852
hello 1853
hello 1854
hello 1855
hello 1856
hello 1857
hello 1858
hello 1859
hello 1860
hello 1861
hello 1862
hello 1863
hello 1864
hello 1865
hello 1866
hello 1867
hello 1868
hello 1869
hello 1870
hello 1871
hello 1872
hello 1873
hello 1874
hello 1875
hello 1876
hello 1877
hello 1878
hello 1879
hello 1880
hello 1881
hello 1882
hello 1883
hello 1884

 44%|████▎     | 2432/5568 [00:00<00:00, 5015.19it/s]

hello 1885
hello 1886
hello 1887
hello 1888
hello 1889
hello 1890
hello 1891
hello 1892
hello 1893
hello 1894
hello 1895
hello 1896
hello 1897
hello 1898
hello 1899
hello 1900
hello 1901
hello 1902
hello 1903
hello 1904
hello 1905
hello 1906
hello 1907
hello 1908
hello 1909
hello 1910
hello 1911
hello 1912
hello 1913
hello 1914
hello 1915
hello 1916
hello 1917
hello 1918
hello 1919
hello 1920
hello 1921
hello 1922
hello 1923
hello 1924
hello 1925
hello 1926
hello 1927
hello 1928
hello 1929
hello 1930
hello 1931
hello 1932
hello 1933
hello 1934
hello 1935
hello 1936
hello 1937
hello 1938
hello 1939
hello 1940
hello 1941
hello 1942
hello 1943
hello 1944
hello 1945
hello 1946
hello 1947
hello 1948
hello 1949
hello 1950
hello 1951
hello 1952
hello 1953
hello 1954
hello 1955
hello 1956
hello 1957
hello 1958
hello 1959
hello 1960
hello 1961
hello 1962
hello 1963
hello 1964
hello 1965
hello 1966
hello 1967
hello 1968
hello 1969
hello 1970
hello 1971
hello 1972
hello 1973
hello 1974
hello 1975
hello 1976
hello 1977
hello 1978
hello 1979
hello 1980
hello 1981
hello 1982
hello 1983
hello 1984
hello 1985
hello 1986
hello 1987
hello 1988
hello 1989
hello 1990
hello 1991
hello 1992
hello 1993
hello 1994
hello 1995
hello 1996
hello 1997
hello 1998
hello 1999
hello 2000
hello 2001
hello 2002
hello 2003
hello 2004
hello 2005
hello 2006
hello 2007
hello 2008
hello 2009
hello 2010
hello 2011
hello 2012
hello 2013
hello 2014
hello 2015
hello 2016
hello 2017
hello 2018
hello 2019
hello 2020
hello 2021
hello 2022
hello 2023
hello 2024
hello 2025
hello 2026
hello 2027
hello 2028
hello 2029
hello 2030
hello 2031
hello 2032
hello 2033
hello 2034
hello 2035
hello 2036
hello 2037
hello 2038
hello 2039
hello 2040
hello 2041
hello 2042
hello 2043
hello 2044
hello 2045
hello 2046
hello 2047
hello 2048
hello 2049
hello 2050
hello 2051
hello 2052
hello 2053
hello 2054
hello 2055
hello 2056
hello 2057
hello 2058
hello 2059
hello 2060
hello 2061
hello 2062
hello 2063
hello 2064
hello 2065
hello 2066
hello 2067
hello 2068
hello 2069
hello 2070
hello 2071
hello 2072
hello 2073
hello 2074
hello 2075
hello 2076
hello 2077
hello 2078
hello 2079
hello 2080
hello 2081
hello 2082
hello 2083
hello 2084
hello 2085
hello 2086
hello 2087
hello 2088
hello 2089
hello 2090
hello 2091
hello 2092
hello 2093
hello 2094
hello 2095
hello 2096
hello 2097
hello 2098
hello 2099
hello 2100
hello 2101
hello 2102
hello 2103
hello 2104
hello 2105
hello 2106
hello 2107
hello 2108
hello 2109
hello 2110
hello 2111
hello 2112
hello 2113
hello 2114
hello 2115
hello 2116
hello 2117
hello 2118
hello 2119
hello 2120
hello 2121
hello 2122
hello 2123
hello 2124
hello 2125
hello 2126
hello 2127
hello 2128
hello 2129
hello 2130
hello 2131
hello 2132
hello 2133
hello 2134
hello 2135
hello 2136
hello 2137
hello 2138
hello 2139
hello 2140
hello 2141
hello 2142
hello 2143
hello 2144
hello 2145
hello 2146
hello 2147
hello 2148
hello 2149
hello 2150
hello 2151
hello 2152
hello 2153
hello 2154
hello 2155
hello 2156
hello 2157
hello 2158
hello 2159
hello 2160
hello 2161
hello 2162
hello 2163
hello 2164
hello 2165
hello 2166
hello 2167
hello 2168
hello 2169
hello 2170
hello 2171
hello 2172
hello 2173
hello 2174
hello 2175
hello 2176
hello 2177
hello 2178
hello 2179
hello 2180
hello 2181
hello 2182
hello 2183
hello 2184
hello 2185
hello 2186
hello 2187
hello 2188
hello 2189
hello 2190
hello 2191
hello 2192
hello 2193
hello 2194
hello 2195
hello 2196
hello 2197
hello 2198
hello 2199
hello 2200
hello 2201
hello 2202
hello 2203
hello 2204
hello 2205
hello 2206
hello 2207
hello 2208
hello 2209
hello 2210
hello 2211
hello 2212
hello 2213
hello 2214
hello 2215
hello 2216
hello 2217
hello 2218
hello 2219
hello 2220
hello 2221
hello 2222
hello 2223
hello 2224
hello 2225
hello 2226
hello 2227
hello 2228
hello 2229
hello 2230
hello 2231
hello 2232
hello 2233
hello 2234
hello 2235
hello 2236
hello 2237
hello 2238
hello 2239
hello 2240
hello 2241
hello 2242
hello 2243
hello 2244
hello 2245
hello 2246
hello 2247
hello 2248
hello 2249
hello 2250
hello 2251
hello 2252
hello 2253
hello 2254
hello 2255
hello 2256
hello 2257
hello 2258
hello 2259
hello 2260
hello 2261
hello 2262
hello 2263
hello 2264
hello 2265
hello 2266
hello 2267
hello 2268
hello 2269
hello 2270
hello 2271
hello 2272
hello 2273
hello 2274
hello 2275
hello 2276
hello 2277
hello 2278
hello 2279
hello 2280
hello 2281
hello 2282
hello 2283
hello 2284
hello 2285
hello 2286
hello 2287
hello 2288
hello 2289
hello 2290
hello 2291
hello 2292
hello 2293
hello 2294
hello 2295
hello 2296
hello 2297
hello 2298
hello 2299
hello 2300
hello 2301
hello 2302
hello 2303
hello 2304
hello 2305
hello 2306
hello 2307
hello 2308
hello 2309
hello 2310
hello 2311
hello 2312
hello 2313
hello 2314
hello 2315
hello 2316
hello 2317
hello 2318
hello 2319
hello 2320
hello 2321
hello 2322
hello 2323
hello 2324
hello 2325
hello 2326
hello 2327
hello 2328
hello 2329
hello 2330
hello 2331
hello 2332
hello 2333
hello 2334
hello 2335
hello 2336
hello 2337
hello 2338
hello 2339
hello 2340
hello 2341
hello 2342
hello 2343
hello 2344
hello 2345
hello 2346
hello 2347
hello 2348
hello 2349
hello 2350
hello 2351
hello 2352
hello 2353
hello 2354
hello 2355
hello 2356
hello 2357
hello 2358
hello 2359
hello 2360
hello 2361
hello 2362
hello 2363
hello 2364
hello 2365
hello 2366
hello 2367
hello 2368
hello 2369
hello 2370
hello 2371
hello 2372
hello 2373
hello 2374
hello 2375
hello 2376
hello 2377
hello 2378
hello 2379
hello 2380
hello 2381
hello 2382
hello 2383
hello 2384
hello 2385
hello 2386
hello 2387
hello 2388
hello 2389
hello 2390
hello 2391
hello 2392
hello 2393
hello 2394
hello 2395
hello 2396
hello 2397
hello 2398
hello 2399
hello 2400
hello 2401
hello 2402
hello 2403
hello 2404
hello 2405
hello 2406
hello 2407
hello 2408
hello 2409
hello 2410
hello 2411
hello 2412
hello 2413
hello 2414
hello 2415
hello 2416
hello 2417
hello 2418
hello 2419
hello 2420
hello 2421
hello 2422
hello 2423
hello 2424
hello 2425
hello 2426
hello 2427
hello 2428
hello 2429
hello 2430
hello 2431
hello 2432
hello 2433
hello 2434
hello 2435
hello 2436
hello 2437
hello 2438
hello 2439
hello 2440
hello 2441
hello 2442
hello 2443
hello 2444
hello 2445
hello 2446
hello 2447
hello 2448
hello 2449
hello 2450
hello 2451
hello 2452
hello 2453
hello 2454
hello 2455
hello 2456
hello 2457
hello 2458
hello 2459
hello 2460
hello 2461
hello 2462
hello 2463
hello 2464
hello 2465
hello 2466
hello 2467
hello 2468
hello 2469
hello 2470
hello 2471
hello 2472
hello 2473
hello 2474
hello 2475
hello 2476
hello 2477
hello 2478
hello 2479
hello 2480
hello 2481
hello 2482
hello 2483
hello 2484
hello 2485
hello 2486
hello 2487
hello 2488
hello 2489
hello 2490
hello 2491
hello 2492
hello 2493
hello 2494
hello 2495
hello 2496
hello 2497
hello 2498
hello 2499
hello 2500
hello 2501
hello 2502
hello 2503
hello 2504
hello 2505
hello 2506
hello 2507
hello 2508
hello 2509
hello 2510
hello 2511
hello 2512
hello 2513
hello 2514
hello 2515
hello 2516
hello 2517
hello 2518
hello 2519
hello 2520
hello 2521
hello 2522
hello 2523
hello 2524
hello 2525
hello 2526
hello 2527
hello 2528
hello 2529
hello 2530
hello 2531
hello 2532
hello 2533
hello 2534
hello 2535
hello 2536
hello 2537
hello 2538
hello 2539
hello 2540
hello 2541
hello 2542
hello 2543
hello 2544
hello 2545
hello 2546
hello 2547
hello 2548
hello 2549
hello 2550
hello 2551
hello 2552
hello 2553
hello 2554
hello 2555
hello 2556
hello 2557
hello 2558
hello 2559
hello 2560
hello 2561
hello 2562
hello 2563
hello 2564
hello 2565
hello 2566
hello 2567
hello 2568
hello 2569
hello 2570
hello 2571
hello 2572
hello 2573
hello 2574
hello 2575
hello 2576
hello 2577
hello 2578
hello 2579
hello 2580
hello 2581
hello 2582
hello 2583
hello 2584
hello 2585
hello 2586
hello 2587
hello 2588
hello 2589
hello 2590
hello 2591
hello 2592
hello 2593
hello 2594
hello 2595
hello 2596
hello 2597
hello 2598
hello 2599
hello 2600
hello 2601
hello 2602
hello 2603
hello 2604
hello 2605
hello 2606
hello 2607
hello 2608
hello 2609
hello 2610
hello 2611
hello 2612
hello 2613
hello 2614
hello 2615
hello 2616
hello 2617
hello 2618
hello 2619
hello 2620
hello 2621
hello 2622
hello 2623
hello 2624
hello 2625
hello 2626
hello 2627
hello 2628
hello 2629
hello 2630
hello 2631
hello 2632
hello 2633
hello 2634
hello 2635
hello 2636
hello 2637
hello 2638
hello 2639
hello 2640
hello 2641
hello 2642
hello 2643
hello 2644
hello 2645
hello 2646
hello 2647
hello 2648
hello 2649
hello 2650
hello 2651
hello 2652
hello 2653
hello 2654
hello 2655
hello 2656
hello 2657
hello 2658
hello 2659
hello 2660
hello 2661
hello 2662
hello 2663
hello 2664
hello 2665
hello 2666
hello 2667
hello 2668
hello 2669
hello 2670
hello 2671
hello 2672
hello 2673
hello 2674
hello 2675
hello 2676
hello 2677
hello 2678
hello 2679
hello 2680
hello 2681
hello 2682
hello 2683
hello 2684
hello 2685
hello 2686
hello 2687
hello 2688
hello 2689
hello 2690
hello 2691
hello 2692
hello 2693
hello 2694
hello 2695
hello 2696
hello 2697
hello 2698
hello 2699
hello 2700
hello 2701
hello 2702
hello 2703
hello 2704
hello 2705
hello 2706
hello 2707
hello 2708
hello 2709
hello 2710
hello 2711
hello 2712
hello 2713
hello 2714
hello 2715
hello 2716
hello 2717
hello 2718
hello 2719
hello 2720
hello 2721
hello 2722
hello 2723
hello 2724
hello 2725
hello 2726
hello 2727
hello 2728
hello 2729
hello 2730
hello 2731
hello 2732
hello 2733
hello 2734
hello 2735
hello 2736
hello 2737
hello 2738
hello 2739
hello 2740
hello 2741
hello 2742
hello 2743
hello 2744
hello 2745
hello 2746
hello 2747
hello 2748
hello 2749
hello 2750
hello 2751
hello 2752
hello 2753
hello 2754
hello 2755
hello 2756
hello 2757
hello 2758
hello 2759
hello 2760
hello 2761
hello 2762
hello 2763
hello 2764
hello 2765
hello 2766
hello 2767
hello 2768
hello 2769
hello 2770
hello 2771
hello 2772
hello 2773
hello 2774
hello 2775
hello 2776
hello 2777
hello 2778
hello 2779
hello 2780
hello 2781
hello 2782
hello 2783
hello 2784
hello 2785
hello 2786
hello 2787
hello 2788
hello 2789
hello 2790
hello 2791
hello 2792
hello 2793
hello 2794
hello 2795
hello 2796
hello 2797
hello 2798
hello 2799
hello 2800
hello 2801
hello 2802
hello 2803
hello 2804
hello 2805
hello 2806
hello 2807
hello 2808
hello 2809
hello 2810
hello 2811
hello 2812
hello 2813
hello 2814
hello 2815
hello 2816
hello 2817
hello 2818
hello 2819
hello 2820
hello 2821
hello 2822
hello 2823
hello 2824
hello 2825
hello 2826
hello 2827
hello 2828
hello 2829
hello 2830
hello 2831
hello 2832
hello 2833
hello 2834
hello 2835
hello 2836
hello 2837
hello 2838
hello 2839
hello 2840
hello 2841
hello 2842
hello 2843
hello 2844
hello 2845
hello 2846
hello 2847
hello 2848
hello 2849
hello 2850
hello 2851
hello 2852
hello 2853
hello 2854
hello 2855
hello 2856
hello 2857
hello 2858
hello 2859
hello 2860
hello 2861
hello 2862
hello 2863
hello 2864
hello 2865
hello 2866
hello 2867
hello 2868
hello 2869
hello 2870
hello 2871
hello 2872
hello 2873
hello 2874
hello 2875
hello 2876
hello 2877
hello 2878
hello 2879
hello 2880
hello 2881
hello 2882
hello 2883
hello 2884
hello 2885
hello 2886
hello 2887
hello 2888
hello 2889
hello 2890
hello 2891
hello 2892
hello 2893
hello 2894
hello 2895
hello 2896
hello 2897
hello 2898
hello 2899
hello 2900
hello 2901
hello 2902
hello 2903
hello 2904
hello 2905
hello 2906
hello 2907
hello 2908
hello 2909
hello 2910
hello 2911
hello 2912
hello 2913
hello 2914
hello 2915
hello 2916
hello 2917
hello 2918
hello 2919
hello 2920
hello 2921
hello 2922
hello 2923
hello 2924
hello 2925
hello 2926
hello 2927
hello 2928
hello 2929
hello 2930
hello 2931
hello 2932
hello 2933
hello 2934
hello 2935
hello 2936
hello 2937
hello 2938
hello 2939
hello 2940
hello 2941
hello 2942
hello 2943
hello 2944
hello 2945
hello 2946
hello 2947
hello 2948
hello 2949
hello 2950
hello 2951
hello 2952
hello 2953
hello 2954
hello 2955
hello 2956
hello 2957
hello 2958
hello 2959
hello 2960
hello 2961
hello 2962
hello 2963
hello 2964
hello 2965
hello 2966
hello 2967
hello 2968
hello 2969
hello 2970
hello 2971
hello 2972
hello 2973
hello 2974
hello 2975
hello 2976
hello 2977
hello 2978
hello 2979
hello 2980
hello 2981
hello 2982
hello 2983
hello 2984
hello 2985
hello 2986
hello 2987
hello 2988
hello 2989
hello 2990
hello 2991
hello 2992
hello 2993
hello 2994
hello 2995
hello 2996
hello 2997
hello 2998
hello 2999
hello 3000
hello 3001
hello 3002
hello 3003
hello 3004
hello 3005
hello 3006
hello 3007
hello 3008
hello 3009
hello 3010
hello 3011
hello 3012
hello 3013
hello 3014
hello 3015
hello 3016
hello 3017
hello 3018
hello 3019
hello 3020
hello 3021
hello 3022
hello 3023
hello 3024
hello 3025
hello 3026
hello 3027
hello 3028
hello 3029
hello 3030
hello 3031
hello 3032
hello 3033
hello 3034
hello 3035
hello 3036
hello 3037
hello 3038
hello 3039
hello 3040
hello 3041
hello 3042
hello 3043
hello 3044
hello 3045
hello 3046
hello 3047
hello 3048
hello 3049
hello 3050
hello 3051
hello 3052
hello 3053
hello 3054
hello 3055
hello 3056
hello 3057
hello 3058
hello 3059
hello 3060
hello 3061
hello 3062
hello 3063
hello 3064
hello 3065
hello 3066
hello 3067
hello 3068
hello 3069
hello 3070
hello 3071
hello 3072
hello 3073
hello 3074
hello 3075
hello 3076
hello 3077
hello 3078

 55%|█████▌    | 3079/5568 [00:00<00:00, 5497.46it/s]

hello 3079
hello 3080
hello 3081
hello 3082
hello 3083
hello 3084
hello 3085
hello 3086
hello 3087
hello 3088
hello 3089
hello 3090
hello 3091
hello 3092
hello 3093
hello 3094
hello 3095
hello 3096
hello 3097
hello 3098
hello 3099
hello 3100
hello 3101
hello 3102
hello 3103
hello 3104
hello 3105
hello 3106
hello 3107
hello 3108
hello 3109
hello 3110
hello 3111
hello 3112
hello 3113
hello 3114
hello 3115
hello 3116
hello 3117
hello 3118
hello 3119
hello 3120
hello 3121
hello 3122
hello 3123
hello 3124
hello 3125
hello 3126
hello 3127
hello 3128
hello 3129
hello 3130
hello 3131
hello 3132
hello 3133
hello 3134
hello 3135
hello 3136
hello 3137
hello 3138
hello 3139
hello 3140
hello 3141
hello 3142
hello 3143
hello 3144
hello 3145
hello 3146
hello 3147
hello 3148
hello 3149
hello 3150
hello 3151
hello 3152
hello 3153
hello 3154
hello 3155
hello 3156
hello 3157
hello 3158
hello 3159
hello 3160
hello 3161
hello 3162
hello 3163
hello 3164
hello 3165
hello 3166
hello 3167
hello 3168
hello 3169
hello 3170
hello 3171
hello 3172
hello 3173
hello 3174
hello 3175
hello 3176
hello 3177
hello 3178
hello 3179
hello 3180
hello 3181
hello 3182
hello 3183
hello 3184
hello 3185
hello 3186
hello 3187
hello 3188
hello 3189
hello 3190
hello 3191
hello 3192
hello 3193
hello 3194
hello 3195
hello 3196
hello 3197
hello 3198
hello 3199
hello 3200
hello 3201
hello 3202
hello 3203
hello 3204
hello 3205
hello 3206
hello 3207
hello 3208
hello 3209
hello 3210
hello 3211
hello 3212
hello 3213
hello 3214
hello 3215
hello 3216
hello 3217
hello 3218
hello 3219
hello 3220
hello 3221
hello 3222
hello 3223
hello 3224
hello 3225
hello 3226
hello 3227
hello 3228
hello 3229
hello 3230
hello 3231
hello 3232
hello 3233
hello 3234
hello 3235
hello 3236
hello 3237
hello 3238
hello 3239
hello 3240
hello 3241
hello 3242
hello 3243
hello 3244
hello 3245
hello 3246
hello 3247
hello 3248
hello 3249
hello 3250
hello 3251
hello 3252
hello 3253
hello 3254
hello 3255
hello 3256
hello 3257
hello 3258
hello 3259
hello 3260
hello 3261
hello 3262
hello 3263
hello 3264
hello 3265
hello 3266
hello 3267
hello 3268
hello 3269
hello 3270
hello 3271
hello 3272
hello 3273
hello 3274
hello 3275
hello 3276
hello 3277
hello 3278
hello 3279
hello 3280
hello 3281
hello 3282
hello 3283
hello 3284
hello 3285
hello 3286
hello 3287
hello 3288
hello 3289
hello 3290
hello 3291
hello 3292
hello 3293
hello 3294
hello 3295
hello 3296
hello 3297
hello 3298
hello 3299
hello 3300
hello 3301
hello 3302
hello 3303
hello 3304
hello 3305
hello 3306
hello 3307
hello 3308
hello 3309
hello 3310
hello 3311
hello 3312
hello 3313
hello 3314
hello 3315
hello 3316
hello 3317
hello 3318
hello 3319
hello 3320
hello 3321
hello 3322
hello 3323
hello 3324
hello 3325
hello 3326
hello 3327
hello 3328
hello 3329
hello 3330
hello 3331
hello 3332
hello 3333
hello 3334
hello 3335
hello 3336
hello 3337
hello 3338
hello 3339
hello 3340
hello 3341
hello 3342
hello 3343
hello 3344
hello 3345
hello 3346
hello 3347
hello 3348
hello 3349
hello 3350
hello 3351
hello 3352
hello 3353
hello 3354
hello 3355
hello 3356
hello 3357
hello 3358
hello 3359
hello 3360
hello 3361
hello 3362
hello 3363
hello 3364
hello 3365
hello 3366
hello 3367
hello 3368
hello 3369
hello 3370
hello 3371
hello 3372
hello 3373
hello 3374
hello 3375
hello 3376
hello 3377
hello 3378
hello 3379
hello 3380
hello 3381
hello 3382
hello 3383
hello 3384
hello 3385
hello 3386
hello 3387
hello 3388
hello 3389
hello 3390
hello 3391
hello 3392
hello 3393
hello 3394
hello 3395
hello 3396
hello 3397
hello 3398
hello 3399
hello 3400
hello 3401
hello 3402
hello 3403
hello 3404
hello 3405
hello 3406
hello 3407
hello 3408
hello 3409
hello 3410
hello 3411
hello 3412
hello 3413
hello 3414
hello 3415
hello 3416
hello 3417
hello 3418
hello 3419
hello 3420
hello 3421
hello 3422
hello 3423
hello 3424
hello 3425
hello 3426
hello 3427
hello 3428
hello 3429
hello 3430
hello 3431
hello 3432
hello 3433
hello 3434
hello 3435
hello 3436
hello 3437
hello 3438
hello 3439
hello 3440
hello 3441

 80%|███████▉  | 4430/5568 [00:00<00:00, 6142.62it/s]

hello 3442
hello 3443
hello 3444
hello 3445
hello 3446
hello 3447
hello 3448
hello 3449
hello 3450
hello 3451
hello 3452
hello 3453
hello 3454
hello 3455
hello 3456
hello 3457
hello 3458
hello 3459
hello 3460
hello 3461
hello 3462
hello 3463
hello 3464
hello 3465
hello 3466
hello 3467
hello 3468
hello 3469
hello 3470
hello 3471
hello 3472
hello 3473
hello 3474
hello 3475
hello 3476
hello 3477
hello 3478
hello 3479
hello 3480
hello 3481
hello 3482
hello 3483
hello 3484
hello 3485
hello 3486
hello 3487
hello 3488
hello 3489
hello 3490
hello 3491
hello 3492
hello 3493
hello 3494
hello 3495
hello 3496
hello 3497
hello 3498
hello 3499
hello 3500
hello 3501
hello 3502
hello 3503
hello 3504
hello 3505
hello 3506
hello 3507
hello 3508
hello 3509
hello 3510
hello 3511
hello 3512
hello 3513
hello 3514
hello 3515
hello 3516
hello 3517
hello 3518
hello 3519
hello 3520
hello 3521
hello 3522
hello 3523
hello 3524
hello 3525
hello 3526
hello 3527
hello 3528
hello 3529
hello 3530
hello 3531
hello 3532
hello 3533
hello 3534
hello 3535
hello 3536
hello 3537
hello 3538
hello 3539
hello 3540
hello 3541
hello 3542
hello 3543
hello 3544
hello 3545
hello 3546
hello 3547
hello 3548
hello 3549
hello 3550
hello 3551
hello 3552
hello 3553
hello 3554
hello 3555
hello 3556
hello 3557
hello 3558
hello 3559
hello 3560
hello 3561
hello 3562
hello 3563
hello 3564
hello 3565
hello 3566
hello 3567
hello 3568
hello 3569
hello 3570
hello 3571
hello 3572
hello 3573
hello 3574
hello 3575
hello 3576
hello 3577
hello 3578
hello 3579
hello 3580
hello 3581
hello 3582
hello 3583
hello 3584
hello 3585
hello 3586
hello 3587
hello 3588
hello 3589
hello 3590
hello 3591
hello 3592
hello 3593
hello 3594
hello 3595
hello 3596
hello 3597
hello 3598
hello 3599
hello 3600
hello 3601
hello 3602
hello 3603
hello 3604
hello 3605
hello 3606
hello 3607
hello 3608
hello 3609
hello 3610
hello 3611
hello 3612
hello 3613
hello 3614
hello 3615
hello 3616
hello 3617
hello 3618
hello 3619
hello 3620
hello 3621
hello 3622
hello 3623
hello 3624
hello 3625
hello 3626
hello 3627
hello 3628
hello 3629
hello 3630
hello 3631
hello 3632
hello 3633
hello 3634
hello 3635
hello 3636
hello 3637
hello 3638
hello 3639
hello 3640
hello 3641
hello 3642
hello 3643
hello 3644
hello 3645
hello 3646
hello 3647
hello 3648
hello 3649
hello 3650
hello 3651
hello 3652
hello 3653
hello 3654
hello 3655
hello 3656
hello 3657
hello 3658
hello 3659
hello 3660
hello 3661
hello 3662
hello 3663
hello 3664
hello 3665
hello 3666
hello 3667
hello 3668
hello 3669
hello 3670
hello 3671
hello 3672
hello 3673
hello 3674
hello 3675
hello 3676
hello 3677
hello 3678
hello 3679
hello 3680
hello 3681
hello 3682
hello 3683
hello 3684
hello 3685
hello 3686
hello 3687
hello 3688
hello 3689
hello 3690
hello 3691
hello 3692
hello 3693
hello 3694
hello 3695
hello 3696
hello 3697
hello 3698
hello 3699
hello 3700
hello 3701
hello 3702
hello 3703
hello 3704
hello 3705
hello 3706
hello 3707
hello 3708
hello 3709
hello 3710
hello 3711
hello 3712
hello 3713
hello 3714
hello 3715
hello 3716
hello 3717
hello 3718
hello 3719
hello 3720
hello 3721
hello 3722
hello 3723
hello 3724
hello 3725
hello 3726
hello 3727
hello 3728
hello 3729
hello 3730
hello 3731
hello 3732
hello 3733
hello 3734
hello 3735
hello 3736
hello 3737
hello 3738
hello 3739
hello 3740
hello 3741
hello 3742
hello 3743
hello 3744
hello 3745
hello 3746
hello 3747
hello 3748
hello 3749
hello 3750
hello 3751
hello 3752
hello 3753
hello 3754
hello 3755
hello 3756
hello 3757
hello 3758
hello 3759
hello 3760
hello 3761
hello 3762
hello 3763
hello 3764
hello 3765
hello 3766
hello 3767
hello 3768
hello 3769
hello 3770
hello 3771
hello 3772
hello 3773
hello 3774
hello 3775
hello 3776
hello 3777
hello 3778
hello 3779
hello 3780
hello 3781
hello 3782
hello 3783
hello 3784
hello 3785
hello 3786
hello 3787
hello 3788
hello 3789
hello 3790
hello 3791
hello 3792
hello 3793
hello 3794
hello 3795
hello 3796
hello 3797
hello 3798
hello 3799
hello 3800
hello 3801
hello 3802
hello 3803
hello 3804
hello 3805
hello 3806
hello 3807
hello 3808
hello 3809
hello 3810
hello 3811
hello 3812
hello 3813
hello 3814
hello 3815
hello 3816
hello 3817
hello 3818
hello 3819
hello 3820
hello 3821
hello 3822
hello 3823
hello 3824
hello 3825
hello 3826
hello 3827
hello 3828
hello 3829
hello 3830
hello 3831
hello 3832
hello 3833
hello 3834
hello 3835
hello 3836
hello 3837
hello 3838
hello 3839
hello 3840
hello 3841
hello 3842
hello 3843
hello 3844
hello 3845
hello 3846
hello 3847
hello 3848
hello 3849
hello 3850
hello 3851
hello 3852
hello 3853
hello 3854
hello 3855
hello 3856
hello 3857
hello 3858
hello 3859
hello 3860
hello 3861
hello 3862
hello 3863
hello 3864
hello 3865
hello 3866
hello 3867
hello 3868
hello 3869
hello 3870
hello 3871
hello 3872
hello 3873
hello 3874
hello 3875
hello 3876
hello 3877
hello 3878
hello 3879
hello 3880
hello 3881
hello 3882
hello 3883
hello 3884
hello 3885
hello 3886
hello 3887
hello 3888
hello 3889
hello 3890
hello 3891
hello 3892
hello 3893
hello 3894
hello 3895
hello 3896
hello 3897
hello 3898
hello 3899
hello 3900
hello 3901
hello 3902
hello 3903
hello 3904
hello 3905
hello 3906
hello 3907
hello 3908
hello 3909
hello 3910
hello 3911
hello 3912
hello 3913
hello 3914
hello 3915
hello 3916
hello 3917
hello 3918
hello 3919
hello 3920
hello 3921
hello 3922
hello 3923
hello 3924
hello 3925
hello 3926
hello 3927
hello 3928
hello 3929
hello 3930
hello 3931
hello 3932
hello 3933
hello 3934
hello 3935
hello 3936
hello 3937
hello 3938
hello 3939
hello 3940
hello 3941
hello 3942
hello 3943
hello 3944
hello 3945
hello 3946
hello 3947
hello 3948
hello 3949
hello 3950
hello 3951
hello 3952
hello 3953
hello 3954
hello 3955
hello 3956
hello 3957
hello 3958
hello 3959
hello 3960
hello 3961
hello 3962
hello 3963
hello 3964
hello 3965
hello 3966
hello 3967
hello 3968
hello 3969
hello 3970
hello 3971
hello 3972
hello 3973
hello 3974
hello 3975
hello 3976
hello 3977
hello 3978
hello 3979
hello 3980
hello 3981
hello 3982
hello 3983
hello 3984
hello 3985
hello 3986
hello 3987
hello 3988
hello 3989
hello 3990
hello 3991
hello 3992
hello 3993
hello 3994
hello 3995
hello 3996
hello 3997
hello 3998
hello 3999
hello 4000
hello 4001
hello 4002
hello 4003
hello 4004
hello 4005
hello 4006
hello 4007
hello 4008
hello 4009
hello 4010
hello 4011
hello 4012
hello 4013
hello 4014
hello 4015
hello 4016
hello 4017
hello 4018
hello 4019
hello 4020
hello 4021
hello 4022
hello 4023
hello 4024
hello 4025
hello 4026
hello 4027
hello 4028
hello 4029
hello 4030
hello 4031
hello 4032
hello 4033
hello 4034
hello 4035
hello 4036
hello 4037
hello 4038
hello 4039
hello 4040
hello 4041
hello 4042
hello 4043
hello 4044
hello 4045
hello 4046
hello 4047
hello 4048
hello 4049
hello 4050
hello 4051
hello 4052
hello 4053
hello 4054
hello 4055
hello 4056
hello 4057
hello 4058
hello 4059
hello 4060
hello 4061
hello 4062
hello 4063
hello 4064
hello 4065
hello 4066
hello 4067
hello 4068
hello 4069
hello 4070
hello 4071
hello 4072
hello 4073
hello 4074
hello 4075
hello 4076
hello 4077
hello 4078
hello 4079
hello 4080
hello 4081
hello 4082
hello 4083
hello 4084
hello 4085
hello 4086
hello 4087
hello 4088
hello 4089
hello 4090
hello 4091
hello 4092
hello 4093
hello 4094
hello 4095
hello 4096
hello 4097
hello 4098
hello 4099
hello 4100
hello 4101
hello 4102
hello 4103
hello 4104
hello 4105
hello 4106
hello 4107
hello 4108
hello 4109
hello 4110
hello 4111
hello 4112
hello 4113
hello 4114
hello 4115
hello 4116
hello 4117
hello 4118
hello 4119
hello 4120
hello 4121
hello 4122
hello 4123
hello 4124
hello 4125
hello 4126
hello 4127
hello 4128
hello 4129
hello 4130
hello 4131
hello 4132
hello 4133
hello 4134
hello 4135
hello 4136
hello 4137
hello 4138
hello 4139
hello 4140
hello 4141
hello 4142
hello 4143
hello 4144
hello 4145
hello 4146
hello 4147
hello 4148
hello 4149
hello 4150
hello 4151
hello 4152
hello 4153
hello 4154
hello 4155
hello 4156
hello 4157
hello 4158
hello 4159
hello 4160
hello 4161
hello 4162
hello 4163
hello 4164
hello 4165
hello 4166
hello 4167
hello 4168
hello 4169
hello 4170
hello 4171
hello 4172
hello 4173
hello 4174
hello 4175
hello 4176
hello 4177
hello 4178
hello 4179
hello 4180
hello 4181
hello 4182
hello 4183
hello 4184
hello 4185
hello 4186
hello 4187
hello 4188
hello 4189
hello 4190
hello 4191
hello 4192
hello 4193
hello 4194
hello 4195
hello 4196
hello 4197
hello 4198
hello 4199
hello 4200
hello 4201
hello 4202
hello 4203
hello 4204
hello 4205
hello 4206
hello 4207
hello 4208
hello 4209
hello 4210
hello 4211
hello 4212
hello 4213
hello 4214
hello 4215
hello 4216
hello 4217
hello 4218
hello 4219
hello 4220
hello 4221
hello 4222
hello 4223
hello 4224
hello 4225
hello 4226
hello 4227
hello 4228
hello 4229
hello 4230
hello 4231
hello 4232
hello 4233
hello 4234
hello 4235
hello 4236
hello 4237
hello 4238
hello 4239
hello 4240
hello 4241
hello 4242
hello 4243
hello 4244
hello 4245
hello 4246
hello 4247
hello 4248
hello 4249
hello 4250
hello 4251
hello 4252
hello 4253
hello 4254
hello 4255
hello 4256
hello 4257
hello 4258
hello 4259
hello 4260
hello 4261
hello 4262
hello 4263
hello 4264
hello 4265
hello 4266
hello 4267
hello 4268
hello 4269
hello 4270
hello 4271
hello 4272
hello 4273
hello 4274
hello 4275
hello 4276
hello 4277
hello 4278
hello 4279
hello 4280
hello 4281
hello 4282
hello 4283
hello 4284
hello 4285
hello 4286
hello 4287
hello 4288
hello 4289
hello 4290
hello 4291
hello 4292
hello 4293
hello 4294
hello 4295
hello 4296
hello 4297
hello 4298
hello 4299
hello 4300
hello 4301
hello 4302
hello 4303
hello 4304
hello 4305
hello 4306
hello 4307
hello 4308
hello 4309
hello 4310
hello 4311
hello 4312
hello 4313
hello 4314
hello 4315
hello 4316
hello 4317
hello 4318
hello 4319
hello 4320
hello 4321
hello 4322
hello 4323
hello 4324
hello 4325
hello 4326
hello 4327
hello 4328
hello 4329
hello 4330
hello 4331
hello 4332
hello 4333
hello 4334
hello 4335
hello 4336
hello 4337
hello 4338
hello 4339
hello 4340
hello 4341
hello 4342
hello 4343
hello 4344
hello 4345
hello 4346
hello 4347
hello 4348
hello 4349
hello 4350
hello 4351
hello 4352
hello 4353
hello 4354
hello 4355
hello 4356
hello 4357
hello 4358
hello 4359
hello 4360
hello 4361
hello 4362
hello 4363
hello 4364
hello 4365
hello 4366
hello 4367
hello 4368
hello 4369
hello 4370
hello 4371
hello 4372
hello 4373
hello 4374
hello 4375
hello 4376
hello 4377
hello 4378
hello 4379
hello 4380
hello 4381
hello 4382
hello 4383
hello 4384
hello 4385
hello 4386
hello 4387
hello 4388
hello 4389
hello 4390
hello 4391
hello 4392
hello 4393
hello 4394
hello 4395
hello 4396
hello 4397
hello 4398
hello 4399
hello 4400
hello 4401
hello 4402
hello 4403
hello 4404
hello 4405
hello 4406
hello 4407
hello 4408
hello 4409
hello 4410
hello 4411
hello 4412
hello 4413
hello 4414
hello 4415
hello 4416
hello 4417
hello 4418
hello 4419
hello 4420
hello 4421
hello 4422
hello 4423
hello 4424
hello 4425
hello 4426
hello 4427
hello 4428
hello 4429
hello 4430
hello 4431
hello 4432
hello 4433
hello 4434
hello 4435
hello 4436
hello 4437
hello 4438
hello 4439
hello 4440
hello 4441
hello 4442
hello 4443
hello 4444
hello 4445
hello 4446
hello 4447
hello 4448
hello 4449
hello 4450
hello 4451
hello 4452
hello 4453
hello 4454
hello 4455
hello 4456
hello 4457
hello 4458
hello 4459
hello 4460
hello 4461
hello 4462
hello 4463
hello 4464
hello 4465
hello 4466
hello 4467
hello 4468
hello 4469
hello 4470
hello 4471
hello 4472
hello 4473
hello 4474
hello 4475
hello 4476
hello 4477
hello 4478
hello 4479
hello 4480
hello 4481
hello 4482
hello 4483
hello 4484
hello 4485
hello 4486
hello 4487
hello 4488
hello 4489
hello 4490
hello 4491
hello 4492
hello 4493
hello 4494
hello 4495
hello 4496
hello 4497
hello 4498
hello 4499
hello 4500
hello 4501
hello 4502
hello 4503
hello 4504
hello 4505
hello 4506
hello 4507
hello 4508
hello 4509
hello 4510
hello 4511
hello 4512
hello 4513
hello 4514
hello 4515
hello 4516
hello 4517
hello 4518
hello 4519
hello 4520
hello 4521
hello 4522
hello 4523
hello 4524
hello 4525
hello 4526
hello 4527
hello 4528
hello 4529
hello 4530
hello 4531
hello 4532
hello 4533
hello 4534
hello 4535
hello 4536
hello 4537
hello 4538
hello 4539
hello 4540
hello 4541
hello 4542
hello 4543
hello 4544
hello 4545
hello 4546
hello 4547
hello 4548
hello 4549
hello 4550
hello 4551
hello 4552
hello 4553
hello 4554
hello 4555
hello 4556
hello 4557
hello 4558
hello 4559
hello 4560
hello 4561
hello 4562
hello 4563
hello 4564
hello 4565
hello 4566
hello 4567
hello 4568
hello 4569
hello 4570
hello 4571
hello 4572
hello 4573
hello 4574
hello 4575
hello 4576
hello 4577
hello 4578
hello 4579
hello 4580
hello 4581
hello 4582
hello 4583
hello 4584
hello 4585
hello 4586
hello 4587
hello 4588
hello 4589
hello 4590
hello 4591
hello 4592
hello 4593
hello 4594
hello 4595
hello 4596
hello 4597
hello 4598
hello 4599
hello 4600
hello 4601
hello 4602
hello 4603
hello 4604
hello 4605
hello 4606
hello 4607
hello 4608
hello 4609
hello 4610
hello 4611
hello 4612
hello 4613
hello 4614
hello 4615
hello 4616
hello 4617
hello 4618
hello 4619
hello 4620
hello 4621
hello 4622
hello 4623
hello 4624
hello 4625
hello 4626
hello 4627
hello 4628
hello 4629
hello 4630
hello 4631
hello 4632
hello 4633
hello 4634
hello 4635
hello 4636
hello 4637
hello 4638
hello 4639
hello 4640
hello 4641
hello 4642
hello 4643
hello 4644
hello 4645
hello 4646
hello 4647
hello 4648
hello 4649
hello 4650
hello 4651
hello 4652
hello 4653
hello 4654
hello 4655
hello 4656
hello 4657
hello 4658
hello 4659
hello 4660
hello 4661
hello 4662
hello 4663
hello 4664
hello 4665
hello 4666
hello 4667
hello 4668
hello 4669
hello 4670
hello 4671
hello 4672
hello 4673
hello 4674
hello 4675
hello 4676
hello 4677
hello 4678
hello 4679
hello 4680
hello 4681
hello 4682
hello 4683
hello 4684
hello 4685
hello 4686
hello 4687
hello 4688
hello 4689
hello 4690
hello 4691
hello 4692
hello 4693
hello 4694
hello 4695
hello 4696
hello 4697
hello 4698
hello 4699
hello 4700
hello 4701
hello 4702
hello 4703
hello 4704
hello 4705
hello 4706
hello 4707
hello 4708
hello 4709
hello 4710
hello 4711
hello 4712
hello 4713
hello 4714
hello 4715
hello 4716
hello 4717
hello 4718
hello 4719
hello 4720
hello 4721
hello 4722
hello 4723
hello 4724
hello 4725
hello 4726
hello 4727
hello 4728
hello 4729
hello 4730
hello 4731
hello 4732
hello 4733
hello 4734
hello 4735
hello 4736
hello 4737
hello 4738
hello 4739
hello 4740
hello 4741
hello 4742
hello 4743
hello 4744
hello 4745
hello 4746
hello 4747
hello 4748
hello 4749
hello 4750
hello 4751
hello 4752
hello 4753
hello 4754
hello 4755
hello 4756
hello 4757
hello 4758
hello 4759
hello 4760
hello 4761
hello 4762
hello 4763
hello 4764
hello 4765
hello 4766
hello 4767
hello 4768
hello 4769
hello 4770
hello 4771
hello 4772
hello 4773
hello 4774
hello 4775
hello 4776
hello 4777
hello 4778
hello 4779
hello 4780
hello 4781
hello 4782
hello 4783
hello 4784
hello 4785
hello 4786
hello 4787
hello 4788
hello 4789
hello 4790
hello 4791
hello 4792
hello 4793
hello 4794
hello 4795
hello 4796
hello 4797
hello 4798
hello 4799
hello 4800
hello 4801
hello 4802
hello 4803
hello 4804
hello 4805
hello 4806
hello 4807
hello 4808
hello 4809
hello 4810
hello 4811
hello 4812
hello 4813
hello 4814
hello 4815
hello 4816
hello 4817
hello 4818
hello 4819
hello 4820
hello 4821
hello 4822
hello 4823
hello 4824
hello 4825
hello 4826
hello 4827
hello 4828
hello 4829
hello 4830
hello 4831
hello 4832
hello 4833
hello 4834
hello 4835
hello 4836
hello 4837
hello 4838
hello 4839
hello 4840
hello 4841
hello 4842
hello 4843
hello 4844
hello 4845
hello 4846
hello 4847
hello 4848
hello 4849
hello 4850
hello 4851
hello 4852
hello 4853
hello 4854
hello 4855
hello 4856
hello 4857
hello 4858
hello 4859
hello 4860
hello 4861
hello 4862
hello 4863
hello 4864
hello 4865
hello 4866
hello 4867
hello 4868
hello 4869
hello 4870
hello 4871
hello 4872
hello 4873
hello 4874
hello 4875
hello 4876
hello 4877
hello 4878
hello 4879
hello 4880
hello 4881
hello 4882
hello 4883
hello 4884
hello 4885
hello 4886
hello 4887
hello 4888
hello 4889
hello 4890
hello 4891
hello 4892
hello 4893
hello 4894
hello 4895
hello 4896
hello 4897
hello 4898
hello 4899
hello 4900
hello 4901
hello 4902
hello 4903
hello 4904
hello 4905
hello 4906
hello 4907
hello 4908
hello 4909
hello 4910
hello 4911
hello 4912
hello 4913
hello 4914
hello 4915
hello 4916
hello 4917
hello 4918
hello 4919
hello 4920
hello 4921
hello 4922
hello 4923
hello 4924
hello 4925
hello 4926
hello 4927
hello 4928
hello 4929
hello 4930
hello 4931
hello 4932
hello 4933
hello 4934
hello 4935
hello 4936
hello 4937
hello 4938
hello 4939
hello 4940
hello 4941
hello 4942
hello 4943
hello 4944
hello 4945
hello 4946
hello 4947
hello 4948
hello 4949
hello 4950
hello 4951
hello 4952
hello 4953
hello 4954
hello 4955
hello 4956
hello 4957
hello 4958
hello 4959
hello 4960
hello 4961
hello 4962
hello 4963
hello 4964
hello 4965
hello 4966
hello 4967
hello 4968
hello 4969
hello 4970
hello 4971
hello 4972
hello 4973
hello 4974
hello 4975
hello 4976
hello 4977
hello 4978
hello 4979
hello 4980
hello 4981
hello 4982
hello 4983
hello 4984
hello 4985
hello 4986
hello 4987
hello 4988
hello 4989
hello 4990
hello 4991
hello 4992
hello 4993
hello 4994
hello 4995
hello 4996
hello 4997
hello 4998
hello 4999
hello 5000
hello 5001
hello 5002
hello 5003
hello 5004
hello 5005
hello 5006
hello 5007
hello 5008
hello 5009
hello 5010
hello 5011
hello 5012
hello 5013
hello 5014
hello 5015
hello 5016
hello 5017
hello 5018
hello 5019
hello 5020
hello 5021
hello 5022
hello 5023
hello 5024
hello 5025
hello 5026
hello 5027
hello 5028
hello 5029
hello 5030
hello 5031
hello 5032
hello 5033
hello 5034
hello 5035
hello 5036
hello 5037
hello 5038
hello 5039
hello 5040
hello 5041
hello 5042
hello 5043
hello 5044

100%|██████████| 5568/5568 [00:00<00:00, 5638.73it/s]

hello 5045
hello 5046
hello 5047
hello 5048
hello 5049
hello 5050
hello 5051
hello 5052
hello 5053
hello 5054
hello 5055
hello 5056
hello 5057
hello 5058
hello 5059
hello 5060
hello 5061
hello 5062
hello 5063
hello 5064
hello 5065
hello 5066
hello 5067
hello 5068
hello 5069
hello 5070
hello 5071
hello 5072
hello 5073
hello 5074
hello 5075
hello 5076
hello 5077
hello 5078
hello 5079
hello 5080
hello 5081
hello 5082
hello 5083
hello 5084
hello 5085
hello 5086
hello 5087
hello 5088
hello 5089
hello 5090
hello 5091
hello 5092
hello 5093
hello 5094
hello 5095
hello 5096
hello 5097
hello 5098
hello 5099
hello 5100
hello 5101
hello 5102
hello 5103
hello 5104
hello 5105
hello 5106
hello 5107
hello 5108
hello 5109
hello 5110
hello 5111
hello 5112
hello 5113
hello 5114
hello 5115
hello 5116
hello 5117
hello 5118
hello 5119
hello 5120
hello 5121
hello 5122
hello 5123
hello 5124
hello 5125
hello 5126
hello 5127
hello 5128
hello 5129
hello 5130
hello 5131
hello 5132
hello 5133
hello 5134
hello 5135
hello 5136
hello 5137
hello 5138
hello 5139
hello 5140
hello 5141
hello 5142
hello 5143
hello 5144
hello 5145
hello 5146
hello 5147
hello 5148
hello 5149
hello 5150
hello 5151
hello 5152
hello 5153
hello 5154
hello 5155
hello 5156
hello 5157
hello 5158
hello 5159
hello 5160
hello 5161
hello 5162
hello 5163
hello 5164
hello 5165
hello 5166
hello 5167
hello 5168
hello 5169
hello 5170
hello 5171
hello 5172
hello 5173
hello 5174
hello 5175
hello 5176
hello 5177
hello 5178
hello 5179
hello 5180
hello 5181
hello 5182
hello 5183
hello 5184
hello 5185
hello 5186
hello 5187
hello 5188
hello 5189
hello 5190
hello 5191
hello 5192
hello 5193
hello 5194
hello 5195
hello 5196
hello 5197
hello 5198
hello 5199
hello 5200
hello 5201
hello 5202
hello 5203
hello 5204
hello 5205
hello 5206
hello 5207
hello 5208
hello 5209
hello 5210
hello 5211
hello 5212
hello 5213
hello 5214
hello 5215
hello 5216
hello 5217
hello 5218
hello 5219
hello 5220
hello 5221
hello 5222
hello 5223
hello 5224
hello 5225
hello 5226
hello 5227
hello 5228
hello 5229
hello 5230
hello 5231
hello 5232
hello 5233
hello 5234
hello 5235
hello 5236
hello 5237
hello 5238
hello 5239
hello 5240
hello 5241
hello 5242
hello 5243
hello 5244
hello 5245
hello 5246
hello 5247
hello 5248
hello 5249
hello 5250
hello 5251
hello 5252
hello 5253
hello 5254
hello 5255
hello 5256
hello 5257
hello 5258
hello 5259
hello 5260
hello 5261
hello 5262
hello 5263
hello 5264
hello 5265
hello 5266
hello 5267
hello 5268
hello 5269
hello 5270
hello 5271
hello 5272
hello 5273
hello 5274
hello 5275
hello 5276
hello 5277
hello 5278
hello 5279
hello 5280
hello 5281
hello 5282
hello 5283
hello 5284
hello 5285
hello 5286
hello 5287
hello 5288
hello 5289
hello 5290
hello 5291
hello 5292
hello 5293
hello 5294
hello 5295
hello 5296
hello 5297
hello 5298
hello 5299
hello 5300
hello 5301
hello 5302
hello 5303
hello 5304
hello 5305
hello 5306
hello 5307
hello 5308
hello 5309
hello 5310
hello 5311
hello 5312
hello 5313
hello 5314
hello 5315
hello 5316
hello 5317
hello 5318
hello 5319
hello 5320
hello 5321
hello 5322
hello 5323
hello 5324
hello 5325
hello 5326
hello 5327
hello 5328
hello 5329
hello 5330
hello 5331
hello 5332
hello 5333
hello 5334
hello 5335
hello 5336
hello 5337
hello 5338
hello 5339
hello 5340
hello 5341
hello 5342
hello 5343
hello 5344
hello 5345
hello 5346
hello 5347
hello 5348
hello 5349
hello 5350
hello 5351
hello 5352
hello 5353
hello 5354
hello 5355
hello 5356
hello 5357
hello 5358
hello 5359
hello 5360
hello 5361
hello 5362
hello 5363
hello 5364
hello 5365
hello 5366
hello 5367
hello 5368
hello 5369
hello 5370
hello 5371
hello 5372
hello 5373
hello 5374
hello 5375
hello 5376
hello 5377
hello 5378
hello 5379
hello 5380
hello 5381
hello 5382
hello 5383
hello 5384
hello 5385
hello 5386
hello 5387
hello 5388
hello 5389
hello 5390
hello 5391
hello 5392
hello 5393
hello 5394
hello 5395
hello 5396
hello 5397
hello 5398
hello 5399
hello 5400
hello 5401
hello 5402
hello 5403
hello 5404
hello 5405
hello 5406
hello 5407
hello 5408
hello 5409
hello 5410
hello 5411
hello 5412
hello 5413
hello 5414
hello 5415
hello 5416
hello 5417
hello 5418
hello 5419
hello 5420
hello 5421
hello 5422
hello 5423
hello 5424
hello 5425
hello 5426
hello 5427
hello 5428
hello 5429
hello 5430
hello 5431
hello 5432
hello 5433
hello 5434
hello 5435
hello 5436
hello 5437
hello 5438
hello 5439
hello 5440
hello 5441
hello 5442
hello 5443
hello 5444
hello 5445
hello 5446
hello 5447
hello 5448
hello 5449
hello 5450
hello 5451
hello 5452
hello 5453
hello 5454
hello 5455
hello 5456
hello 5457
hello 5458
hello 5459
hello 5460
hello 5461
hello 5462
hello 5463
hello 5464
hello 5465
hello 5466
hello 5467
hello 5468
hello 5469
hello 5470
hello 5471
hello 5472
hello 5473
hello 5474
hello 5475
hello 5476
hello 5477
hello 5478
hello 5479
hello 5480
hello 5481
hello 5482
hello 5483
hello 5484
hello 5485
hello 5486
hello 5487
hello 5488
hello 5489
hello 5490
hello 5491
hello 5492
hello 5493
hello 5494
hello 5495
hello 5496
hello 5497
hello 5498
hello 5499
hello 5500
hello 5501
hello 5502
hello 5503
hello 5504
hello 5505
hello 5506
hello 5507
hello 5508
hello 5509
hello 5510
hello 5511
hello 5512
hello 5513
hello 5514
hello 5515
hello 5516
hello 5517
hello 5518
hello 5519
hello 5520
hello 5521
hello 5522
hello 5523
hello 5524
hello 5525
hello 5526
hello 5527
hello 5528
hello 5529
hello 5530
hello 5531
hello 5532
hello 5533
hello 5534
hello 5535
hello 5536
hello 5537
hello 5538
hello 5539
hello 5540
hello 5541
hello 5542
hello 5543
hello 5544
hello 5545
hello 5546
hello 5547
hello 5548
hello 5549
hello 5550
hello 5551
hello 5552
hello 5553
hello 5554
hello 5555
hello 5556
hello 5557
hello 5558
hello 5559
hello 5560
hello 5561
hello 5562
hello 5563
hello 5564
hello 5565
hello 5566
hello 5567

In [54]:
X

[array([-0.15199223,  0.27241415,  0.09593995,  0.03639557,  0.06981777,
        -0.47477445,  0.13610995,  0.43479967, -0.18583742, -0.10268202,
        -0.15803576, -0.34978583, -0.08387049,  0.04645236,  0.21860914,
        -0.19049618,  0.0907877 , -0.22674212, -0.0862565 , -0.44287562,
         0.24751717,  0.15645236,  0.10953552, -0.13620187, -0.07758911,
         0.07581006, -0.2860473 , -0.3043904 , -0.22721052,  0.09445439,
         0.27278322,  0.02571584,  0.13812655, -0.23116972, -0.11188923,
         0.2859863 ,  0.00622673, -0.14631917, -0.13815823, -0.36342928,
         0.04384527, -0.2244742 , -0.12952447,  0.03921323,  0.23724791,
        -0.03496383, -0.1800379 , -0.07145933,  0.10016189,  0.21785945,
         0.08639053, -0.19090672, -0.10755674, -0.01982232, -0.06514939,
         0.12248519,  0.10575698,  0.04940713, -0.2627247 ,  0.11888457,
         0.02689304,  0.06878939, -0.05083815, -0.09431162, -0.24472955,
         0.27154124,  0.0938355 ,  0.19120015, -0.30030426,  0.2945068 ,
        -0.14282939,  0.08876019,  0.2552812 , -0.14446004,  0.25285843,
         0.13442759,  0.02112188, -0.05243954, -0.15853426,  0.05804357,
        -0.15549204,  0.01221487, -0.16133857,  0.28532407, -0.13178878,
         0.01866897,  0.10676554,  0.22916363,  0.27780965, -0.02767263,
         0.27771753,  0.12515925,  0.0574971 ,  0.0100568 ,  0.36009046,
         0.22663558,  0.06309903, -0.1868196 ,  0.07759786, -0.05399752],
       dtype=float32),
 array([-0.15545627,  0.3265416 ,  0.13351475,  0.06088729,  0.09124532,
        -0.59028906,  0.17115879,  0.5042412 , -0.23524202, -0.15186638,
        -0.20719185, -0.43555441, -0.11809447,  0.05070776,  0.2578921 ,
        -0.22566813,  0.10739543, -0.29968292, -0.12792219, -0.542392  ,
         0.25014484,  0.219727  ,  0.13500957, -0.17742077, -0.07138359,
         0.12086685, -0.3510403 , -0.32457453, -0.26366413,  0.12055071,
         0.3012039 ,  0.03993148,  0.16205701, -0.26244432, -0.11819715,
         0.3858832 ,  0.04307574, -0.21122707, -0.18148135, -0.4407759 ,
         0.02046878, -0.28478494, -0.17774948,  0.02282085,  0.2783366 ,
        -0.05148832, -0.20698947, -0.0593814 ,  0.12265889,  0.22494674,
         0.06378761, -0.28248975, -0.09660611, -0.00306854, -0.08013824,
         0.14488448,  0.09564276,  0.06364454, -0.30460888,  0.17705196,
         0.01222061,  0.04867542, -0.04083146, -0.137599  , -0.30200252,
         0.32284987,  0.10093301,  0.24985036, -0.3513342 ,  0.3479656 ,
        -0.2038941 ,  0.13563743,  0.29015854, -0.19930953,  0.28904817,
         0.18201184,  0.05870551, -0.06675071, -0.18440905,  0.04359595,
        -0.17193708,  0.01242958, -0.18344975,  0.33262673, -0.10948317,
         0.02395447,  0.09860609,  0.24506098,  0.33321607, -0.01495509,
         0.31771117,  0.15615936,  0.04623273,  0.02070643,  0.42506483,
         0.2644265 ,  0.04946055, -0.23879848,  0.13335003, -0.06044017],
       dtype=float32),
 array([-0.24972017,  0.43201736,  0.15073095,  0.05335764,  0.10925661,
        -0.7287553 ,  0.22316565,  0.68166   , -0.30570036, -0.17288126,
        -0.24627161, -0.5534383 , -0.11152244,  0.08537827,  0.3437248 ,
        -0.28636703,  0.14058086, -0.3481896 , -0.13139579, -0.7076233 ,
         0.39708477,  0.25442317,  0.17652647, -0.21140535, -0.1239104 ,
         0.1192871 , -0.4441371 , -0.47859472, -0.35337877,  0.147523  ,
         0.42245418,  0.04516375,  0.21571456, -0.36417383, -0.18100259,
         0.45399   ,  0.00910729, -0.21943638, -0.21854104, -0.5597952 ,
         0.07811374, -0.33562502, -0.18741073,  0.06970347,  0.37867117,
        -0.05056703, -0.26666167, -0.11920448,  0.15687118,  0.33280548,
         0.13839643, -0.29605702, -0.17630938, -0.04974756, -0.09075551,
         0.17961575,  0.16441682,  0.07634399, -0.40821046,  0.18052681,
         0.04145901,  0.11172497, -0.08348385, -0.1421879 , -0.3803676 ,
         0.43000215,  0.14884289,  0.2895131 , -0.4693007 ,  0.4518828 ,
        -0.21492293,  0.12853906,  0.402575  , -0.21342282,  0.3912541 ,
         0.21004994,  0.03714022, -0.08205409, -0.24811508,  0.10385902,
        -0.24825965,  0.01099156, -0.25343695,  0.44953346, -0.20606945,
         0.02903827,  0.1739588 ,  0.36375365,  0.44314748, -0.04509905,
         0.4355312 ,  0.19479613,  0.09231432,  0.02202996,  0.55909795,
         0.3690247 ,  0.10505988, -0.28816515,  0.11800475, -0.07877384],
       dtype=float32),
 array([-0.21863063,  0.3589519 ,  0.13338815,  0.04305812,  0.10803375,
        -0.6178351 ,  0.18702519,  0.5805729 , -0.2583106 , -0.155362  ,
        -0.21080124, -0.47281194, -0.09805214,  0.07019772,  0.29278973,
        -0.24762897,  0.12940998, -0.30232608, -0.1109888 , -0.6039782 ,
         0.33157718,  0.21330152,  0.15339494, -0.17910974, -0.09172189,
         0.10099357, -0.37429038, -0.3906523 , -0.3026643 ,  0.12597206,
         0.3607217 ,  0.03963396,  0.18066686, -0.31239834, -0.15948646,
         0.38863167,  0.01680451, -0.1864726 , -0.17194454, -0.47574005,
         0.06700383, -0.29407713, -0.15742047,  0.06522723,  0.3101837 ,
        -0.03756791, -0.2198322 , -0.10262159,  0.11695351,  0.28274497,
         0.11157128, -0.25466987, -0.14405786, -0.03057375, -0.07764496,
         0.15358718,  0.13749605,  0.0660106 , -0.34108683,  0.16226056,
         0.03724053,  0.09117511, -0.06873316, -0.11795538, -0.31974867,
         0.35651398,  0.1240527 ,  0.24502806, -0.3808531 ,  0.38061008,
        -0.17611511,  0.1084902 ,  0.33918837, -0.18392336,  0.32841292,
         0.16387871,  0.02437758, -0.06670859, -0.20368765,  0.07807419,
        -0.20229612,  0.01787013, -0.21051271,  0.37964335, -0.16461782,
         0.04193639,  0.15742047,  0.30167636,  0.3671995 , -0.03802658,
         0.37082672,  0.15607072,  0.0767024 ,  0.01862336,  0.46570098,
         0.3142234 ,  0.08487102, -0.25390387,  0.10375334, -0.07479011],
       dtype=float32),
 array([-0.21890695,  0.38525197,  0.1426569 ,  0.04982481,  0.11216692,
        -0.67192906,  0.20041896,  0.614442  , -0.276946  , -0.1733286 ,
        -0.22582218, -0.5079312 , -0.11172434,  0.08109412,  0.30682373,
        -0.2578152 ,  0.13387209, -0.3257554 , -0.12605976, -0.6410901 ,
         0.34032667,  0.22900704,  0.16351336, -0.20095137, -0.09274414,
         0.11868832, -0.39808318, -0.40399978, -0.31547943,  0.13531727,
         0.3789269 ,  0.03989588,  0.19654027, -0.32951018, -0.15799803,
         0.42650986,  0.0296864 , -0.2102009 , -0.1946026 , -0.50946176,
         0.05295568, -0.3182274 , -0.18078801,  0.05055192,  0.3313795 ,
        -0.04768306, -0.23687221, -0.09769422,  0.13253291,  0.28740427,
         0.11331428, -0.28608337, -0.14109306, -0.03166874, -0.0822404 ,
         0.16681923,  0.1361069 ,  0.06769816, -0.36418045,  0.17951804,
         0.0279786 ,  0.08150068, -0.06615971, -0.13833869, -0.34475905,
         0.3796229 ,  0.13078618,  0.2694813 , -0.41096273,  0.410428  ,
        -0.20446421,  0.12414422,  0.35792705, -0.20111902,  0.3508884 ,
         0.18401279,  0.04065206, -0.07373545, -0.21166593,  0.07591379,
        -0.21939982,  0.0181204 , -0.22359046,  0.39854398, -0.16293456,
         0.03209699,  0.15506032,  0.31071904,  0.39988598, -0.02894081,
         0.38991705,  0.17426383,  0.07900835,  0.0177226 ,  0.49923533,
         0.332379  ,  0.08243395, -0.2663919 ,  0.12578334, -0.07564427],
       dtype=float32),
 array([-0.24070181,  0.40752453,  0.15247521,  0.04566395,  0.11518396,
        -0.6975619 ,  0.20807204,  0.65385014, -0.29322034, -0.1771488 ,
        -0.2316655 , -0.5288083 , -0.10333894,  0.08930109,  0.3280356 ,
        -0.2742873 ,  0.14154868, -0.3295792 , -0.12945382, -0.6783902 ,
         0.37440243,  0.23771724,  0.17549352, -0.21146046, -0.10344463,
         0.11640124, -0.41971806, -0.43658942, -0.3382495 ,  0.14218096,
         0.4041308 ,  0.04445478,  0.21276931, -0.35555762, -0.17784545,
         0.4425493 ,  0.01776312, -0.2073087 , -0.20262504, -0.5360292 ,
         0.06434999, -0.32899266, -0.18091   ,  0.06220778,  0.35822302,
        -0.04706792, -0.25003168, -0.11500858,  0.13958995,  0.31418815,
         0.12986937, -0.28504062, -0.16742362, -0.0439215 , -0.08420802,
         0.17376629,  0.14944424,  0.06794285, -0.38806453,  0.17473218,
         0.03553164,  0.0983999 , -0.07908355, -0.1368866 , -0.36271504,
         0.4045891 ,  0.1386913 ,  0.27882126, -0.4360683 ,  0.4316744 ,
        -0.20252351,  0.12354962,  0.3890957 , -0.1983899 ,  0.37048468,
         0.1850252 ,  0.03673068, -0.08232988, -0.2239773 ,  0.09696996,
        -0.2395062 ,  0.01315615, -0.23924974,  0.42871395, -0.18605915,
         0.03286948,  0.1722116 ,  0.33820918,  0.4238378 , -0.03158002,
         0.41857883,  0.18097247,  0.08884045,  0.01693264,  0.53133875,
         0.3598358 ,  0.09809255, -0.27580884,  0.11738598, -0.08568057],
       dtype=float32),
 array([-0.15719062,  0.31465533,  0.12339348,  0.04533791,  0.07943066,
        -0.5476085 ,  0.1587954 ,  0.4848809 , -0.21842429, -0.1457771 ,
        -0.18252625, -0.41307998, -0.09295052,  0.05632644,  0.24995385,
        -0.2040118 ,  0.09830462, -0.26812434, -0.11006555, -0.51343524,
         0.25767937,  0.1930718 ,  0.12880062, -0.16621   , -0.07546179,
         0.11226139, -0.31638438, -0.31748733, -0.24740219,  0.10820061,
         0.29693937,  0.03103239,  0.1550833 , -0.25381032, -0.12437413,
         0.35746694,  0.03710435, -0.18540755, -0.16731854, -0.40832496,
         0.0240206 , -0.25867182, -0.15612748,  0.02568145,  0.2628991 ,
        -0.03920299, -0.1948268 , -0.06961595,  0.10930573,  0.22352585,
         0.08370322, -0.24809842, -0.11007114, -0.02608596, -0.05857261,
         0.13279973,  0.08867615,  0.05896704, -0.29205522,  0.14732966,
         0.00257523,  0.05466149, -0.04720772, -0.12750171, -0.28729436,
         0.3021706 ,  0.09599409,  0.21463618, -0.33055753,  0.3326515 ,
        -0.17312261,  0.11423243,  0.27821255, -0.1706607 ,  0.27543768,
         0.16995329,  0.05516205, -0.07448722, -0.1680044 ,  0.06036177,
        -0.17358302,  0.00743687, -0.17634061,  0.32091933, -0.11921491,
         0.01624134,  0.09978078,  0.2423482 ,  0.32898667, -0.02150377,
         0.3102633 ,  0.14620443,  0.05866773,  0.01508052,  0.39994466,
         0.2570615 ,  0.06518255, -0.21340466,  0.11546683, -0.06420544],
       dtype=float32),
 array([-0.17358084,  0.35349652,  0.15640591,  0.06768093,  0.10225788,
        -0.63750064,  0.19470061,  0.54203457, -0.24577387, -0.1771284 ,
        -0.22480598, -0.4695029 , -0.12447971,  0.06235499,  0.28276768,
        -0.24347764,  0.10987543, -0.31999856, -0.14183335, -0.5852003 ,
         0.27266145,  0.22565694,  0.14605446, -0.19597483, -0.09056219,
         0.12704109, -0.37063447, -0.3461893 , -0.26698837,  0.13190329,
         0.33861306,  0.03233935,  0.1681956 , -0.27423027, -0.13725643,
         0.4038106 ,  0.05239147, -0.22565272, -0.19256178, -0.47486138,
         0.03674673, -0.3100559 , -0.17898196,  0.03335952,  0.29382825,
        -0.04986494, -0.21687914, -0.06553724,  0.12788467,  0.23771568,
         0.08973484, -0.30832517, -0.10597247, -0.00796051, -0.0815822 ,
         0.1524411 ,  0.11108745,  0.07396065, -0.3277153 ,  0.19198689,
        -0.00236305,  0.05057497, -0.04677181, -0.1525998 , -0.32312533,
         0.34534243,  0.11459854,  0.2503249 , -0.3747585 ,  0.37479532,
        -0.21816555,  0.13793643,  0.30472663, -0.20881832,  0.30657372,
         0.19257376,  0.07399157, -0.0784957 , -0.19495912,  0.0453273 ,
        -0.19147946,  0.01749892, -0.19692633,  0.35688818, -0.10613957,
         0.03078265,  0.10665542,  0.25738543,  0.36102748, -0.03133417,
         0.34579512,  0.15768592,  0.04176973,  0.00447316,  0.4635155 ,
         0.27376685,  0.04553287, -0.26426542,  0.14706624, -0.05635752],
       dtype=float32),
 array([-0.1864319 ,  0.41347495,  0.17540224,  0.07842524,  0.11020092,
        -0.7389749 ,  0.2066106 ,  0.6305563 , -0.2891522 , -0.19709344,
        -0.25921068, -0.5510658 , -0.15099664,  0.0647701 ,  0.3323451 ,
        -0.2743269 ,  0.1213183 , -0.37241974, -0.16048811, -0.6780836 ,
         0.30557084,  0.27308628,  0.17276451, -0.22241263, -0.08532755,
         0.15871325, -0.42994326, -0.40087458, -0.32705718,  0.15130502,
         0.37734044,  0.04144035,  0.20722948, -0.32102054, -0.14901318,
         0.49286926,  0.06590134, -0.27793854, -0.24002416, -0.5486544 ,
         0.01567676, -0.358391  , -0.23261221,  0.01520341,  0.35441375,
        -0.06180055, -0.26297608, -0.07424939,  0.15612793,  0.2786421 ,
         0.08545658, -0.36655205, -0.1216552 , -0.01361542, -0.09193505,
         0.18028936,  0.10481828,  0.0816127 , -0.37842628,  0.21480267,
         0.0050191 ,  0.05388136, -0.04643982, -0.18081965, -0.3896829 ,
         0.40377888,  0.13042036,  0.31266987, -0.44715422,  0.4521082 ,
        -0.25255328,  0.17900726,  0.36208943, -0.25327277,  0.35926414,
         0.24717703,  0.08946019, -0.09634139, -0.22934933,  0.06371611,
        -0.22124454,  0.00945622, -0.23410057,  0.42238313, -0.13351089,
         0.01482668,  0.10811064,  0.30187133,  0.431871  , -0.01819974,
         0.40178365,  0.20153926,  0.06498515,  0.02538932,  0.54331225,
         0.32891405,  0.06461876, -0.29132402,  0.16360141, -0.07987757],
       dtype=float32),
 array([-0.22566515,  0.37327272,  0.13608418,  0.0430951 ,  0.11331607,
        -0.64946383,  0.19143124,  0.60421276, -0.26364532, -0.16652775,
        -0.21948408, -0.4923144 , -0.09971952,  0.07754327,  0.30318442,
        -0.25973973,  0.13508804, -0.31743595, -0.11879764, -0.63000405,
         0.34019783,  0.22152716,  0.15529321, -0.19406757, -0.09548767,
         0.10988496, -0.3867006 , -0.39748934, -0.30464253,  0.13344055,
         0.37177625,  0.0396779 ,  0.18772516, -0.32127628, -0.16190933,
         0.40848985,  0.02379563, -0.19807497, -0.17845339, -0.49537793,
         0.06254499, -0.30750328, -0.16760811,  0.05779038,  0.3183394 ,
        -0.0410118 , -0.22257794, -0.10294336,  0.12450127,  0.28407335,
         0.11653584, -0.2700599 , -0.14209484, -0.02805314, -0.07692543,
         0.1638729 ,  0.14170167,  0.06282625, -0.35006827,  0.1699792 ,
         0.03254275,  0.08495546, -0.0672095 , -0.12689799, -0.3313826 ,
         0.36821935,  0.12945753,  0.25470224, -0.39610505,  0.39539292,
        -0.1895417 ,  0.10969479,  0.35354447, -0.18595298,  0.33811295,
         0.17472748,  0.03147432, -0.06924378, -0.20762129,  0.07840507,
        -0.21190941,  0.02023059, -0.21557021,  0.38952613, -0.16154297,
         0.03718866,  0.15728883,  0.30813777,  0.38885856, -0.03103592,
         0.38560158,  0.16349475,  0.07865556,  0.01433475,  0.48574847,
         0.32738882,  0.08568212, -0.26086062,  0.11553997, -0.07529628],
       dtype=float32),
 array([-0.19951898,  0.3870329 ,  0.15974559,  0.07229821,  0.11907637,
        -0.709079  ,  0.20749214,  0.6049246 , -0.28199014, -0.18384029,
        -0.24830121, -0.5227117 , -0.13110672,  0.06675075,  0.31277597,
        -0.27351093,  0.13551462, -0.35615718, -0.15498883, -0.6528033 ,
         0.30418164,  0.26017845,  0.15781945, -0.21505255, -0.08096875,
         0.14100787, -0.41321674, -0.3877879 , -0.31614912,  0.14526448,
         0.36566558,  0.04564784,  0.19007969, -0.31291974, -0.14762138,
         0.45945725,  0.05032031, -0.24985507, -0.21226616, -0.5275769 ,
         0.03184268, -0.341964  , -0.202207  ,  0.03000365,  0.32660785,
        -0.05911305, -0.24807638, -0.07414195,  0.14090508,  0.26598567,
         0.08273599, -0.33416122, -0.11609253, -0.00828961, -0.09537383,
         0.17025824,  0.12280386,  0.07786014, -0.36256135,  0.21505553,
         0.01300958,  0.05784912, -0.05128633, -0.16207995, -0.35934603,
         0.3842482 ,  0.12118219,  0.29567492, -0.41747308,  0.41779125,
        -0.23713292,  0.15261522,  0.34352624, -0.23516464,  0.34349412,
         0.2068789 ,  0.07360891, -0.07493088, -0.2216016 ,  0.04917141,
        -0.20801733,  0.01737123, -0.21718875,  0.39695224, -0.12626927,
         0.03518149,  0.12408185,  0.29449525,  0.3985104 , -0.02490707,
         0.38531366,  0.1853203 ,  0.0511459 ,  0.02369241,  0.50295854,
         0.3180142 ,  0.05958994, -0.29244414,  0.16370267, -0.07062561],
       dtype=float32),
 array([-0.20726828,  0.4116064 ,  0.17448463,  0.07441787,  0.11743958,
        -0.74017817,  0.22129902,  0.62858415, -0.28954056, -0.19430469,
        -0.2574147 , -0.5521113 , -0.14517736,  0.06552992,  0.33101037,
        -0.27606153,  0.13202249, -0.371912  , -0.15968168, -0.6776975 ,
         0.312099  ,  0.26990458,  0.16915663, -0.22773652, -0.09519663,
         0.15272006, -0.432854  , -0.4051983 , -0.32162204,  0.15218459,
         0.39338055,  0.0367924 ,  0.20177366, -0.32581893, -0.15576792,
         0.47643647,  0.0597577 , -0.26047584, -0.22136256, -0.5541852 ,
         0.03910298, -0.36411002, -0.21407442,  0.03308844,  0.3469813 ,
        -0.05872745, -0.25497398, -0.07872588,  0.14986199,  0.27681738,
         0.09666943, -0.35735145, -0.12283026, -0.0135715 , -0.09955189,
         0.17983164,  0.13015687,  0.08139591, -0.38696474,  0.21758175,
         0.00448732,  0.05969688, -0.04641172, -0.17291299, -0.37997997,
         0.40135926,  0.13002098,  0.30296466, -0.43692186,  0.43671232,
        -0.25181293,  0.15968901,  0.36357656, -0.24333015,  0.36010635,
         0.22546874,  0.08039443, -0.08599716, -0.23178284,  0.05783597,
        -0.22344612,  0.01712599, -0.22881834,  0.42026013, -0.12740201,
         0.03208081,  0.12440357,  0.30821142,  0.424045  , -0.0289644 ,
         0.40036988,  0.1941057 ,  0.06016219,  0.01670732,  0.5377459 ,
         0.32903844,  0.06664389, -0.30017215,  0.16799502, -0.07014073],
       dtype=float32),
 array([-0.22548245,  0.37891844,  0.14165035,  0.04647679,  0.11181006,
        -0.6607371 ,  0.19520892,  0.61030376, -0.2704682 , -0.17229854,
        -0.21745221, -0.50507   , -0.0998426 ,  0.08000091,  0.3070861 ,
        -0.25269687,  0.13391075, -0.31881356, -0.12663959, -0.6316104 ,
         0.3421285 ,  0.2287937 ,  0.15953292, -0.20262215, -0.09252865,
         0.11811601, -0.38755134, -0.39910963, -0.30984798,  0.13143162,
         0.37655565,  0.04065003,  0.19050883, -0.32359827, -0.16062406,
         0.42347324,  0.03229816, -0.2042682 , -0.1873915 , -0.4972604 ,
         0.0544468 , -0.3097068 , -0.17566897,  0.04900846,  0.32603154,
        -0.03820148, -0.23321903, -0.09970362,  0.1283224 ,  0.28657413,
         0.11986623, -0.27935392, -0.14412592, -0.03610123, -0.07507965,
         0.16409333,  0.13261202,  0.06728582, -0.35565853,  0.1708661 ,
         0.01932093,  0.0812014 , -0.06375279, -0.14139885, -0.34521136,
         0.37070364,  0.12907135,  0.25873667, -0.40458137,  0.40509382,
        -0.19310693,  0.11658859,  0.35683548, -0.190457  ,  0.34147578,
         0.18042812,  0.04638342, -0.07931691, -0.20768867,  0.08224615,
        -0.22195631,  0.0190877 , -0.21604054,  0.39262214, -0.1599339 ,
         0.02880301,  0.14932321,  0.3097082 ,  0.40168554, -0.02967823,
         0.3888527 ,  0.17306414,  0.08094995,  0.01699113,  0.49371347,
         0.334223  ,  0.09049858, -0.25882894,  0.12462885, -0.07805834],
       dtype=float32),
 array([-0.20865192,  0.37449405,  0.14219828,  0.0451524 ,  0.10521939,
        -0.65030164,  0.18840641,  0.585666  , -0.2603963 , -0.16626264,
        -0.22121046, -0.4983519 , -0.1092669 ,  0.07451866,  0.29908326,
        -0.25003216,  0.12078449, -0.3147133 , -0.12893334, -0.61589617,
         0.32524014,  0.23104341,  0.1524716 , -0.19971596, -0.09255031,
         0.1209318 , -0.38807666, -0.385321  , -0.30129418,  0.12857193,
         0.34968284,  0.03725075,  0.18708824, -0.3116578 , -0.15406324,
         0.41808924,  0.036488  , -0.2117719 , -0.1969117 , -0.48287115,
         0.04525691, -0.30967492, -0.16960575,  0.05149196,  0.3293971 ,

In [55]:
len(X)

5568

In [56]:
X=np.array(X)

X

array([[-0.15199223,  0.27241415,  0.09593995, ..., -0.1868196 ,
         0.07759786, -0.05399752],
       [-0.15545627,  0.3265416 ,  0.13351475, ..., -0.23879848,
         0.13335003, -0.06044017],
       [-0.24972017,  0.43201736,  0.15073095, ..., -0.28816515,
         0.11800475, -0.07877384],
       ...,
       [-0.2499866 ,  0.433281  ,  0.15583126, ..., -0.27451062,
         0.12330897, -0.09052633],
       [-0.21856706,  0.3825891 ,  0.14222012, ..., -0.25626722,
         0.11735053, -0.07998827],
       [-0.24419622,  0.4118332 ,  0.14466883, ..., -0.28344795,
         0.13361013, -0.07607301]])

In [57]:
X.shape

(5568, 100)

In [58]:
X[0].shape

(100,)

In [60]:
X[0]

array([-0.15199223,  0.27241415,  0.09593995,  0.03639557,  0.06981777,
       -0.47477445,  0.13610995,  0.43479967, -0.18583742, -0.10268202,
       -0.15803576, -0.34978583, -0.08387049,  0.04645236,  0.21860914,
       -0.19049618,  0.0907877 , -0.22674212, -0.0862565 , -0.44287562,
        0.24751717,  0.15645236,  0.10953552, -0.13620187, -0.07758911,
        0.07581006, -0.28604731, -0.3043904 , -0.22721052,  0.09445439,
        0.27278322,  0.02571584,  0.13812655, -0.23116972, -0.11188923,
        0.2859863 ,  0.00622673, -0.14631917, -0.13815823, -0.36342928,
        0.04384527, -0.22447421, -0.12952447,  0.03921323,  0.23724791,
       -0.03496383, -0.1800379 , -0.07145933,  0.10016189,  0.21785945,
        0.08639053, -0.19090672, -0.10755674, -0.01982232, -0.06514939,
        0.12248519,  0.10575698,  0.04940713, -0.2627247 ,  0.11888457,
        0.02689304,  0.06878939, -0.05083815, -0.09431162, -0.24472955,
        0.27154124,  0.0938355 ,  0.19120015, -0.30030426,  0.29450679,
       -0.14282939,  0.08876019,  0.25528121, -0.14446004,  0.25285843,
        0.13442759,  0.02112188, -0.05243954, -0.15853426,  0.05804357,
       -0.15549204,  0.01221487, -0.16133857,  0.28532407, -0.13178878,
        0.01866897,  0.10676554,  0.22916363,  0.27780965, -0.02767263,
        0.27771753,  0.12515925,  0.0574971 ,  0.0100568 ,  0.36009046,
        0.22663558,  0.06309903, -0.1868196 ,  0.07759786, -0.05399752])

In [61]:
messages['label']=messages['label'].map({'spam':1,'ham':0})

In [62]:
messages

      label                                            message
0         0                      Ok lar... Joking wif u oni...
1         1  Free entry in 2 a wkly comp to win FA Cup fina...
2         0  U dun say so early hor... U c already then say...
3         0  Nah I don't think he goes to usf, he lives aro...
4         1  FreeMsg Hey there darling it's been 3 week's n...
...     ...                                                ...
5566      1  This is the 2nd time we have tried 2 contact u...
5567      0               Will ü b going to esplanade fr home?
5568      0  Pity, * was in mood for that. So...any other s...
5569      0  The guy did some bitching but I acted like i'd...
5570      0                         Rofl. Its true to its name

[5571 rows x 2 columns]

In [63]:
y=messages['label']

In [64]:
y

0       0
1       1
2       0
3       0
4       1
       ..
5566    1
5567    0
5568    0
5569    0
5570    0
Name: label, Length: 5571, dtype: int64

In [65]:
X[0]

array([-0.15199223,  0.27241415,  0.09593995,  0.03639557,  0.06981777,
       -0.47477445,  0.13610995,  0.43479967, -0.18583742, -0.10268202,
       -0.15803576, -0.34978583, -0.08387049,  0.04645236,  0.21860914,
       -0.19049618,  0.0907877 , -0.22674212, -0.0862565 , -0.44287562,
        0.24751717,  0.15645236,  0.10953552, -0.13620187, -0.07758911,
        0.07581006, -0.28604731, -0.3043904 , -0.22721052,  0.09445439,
        0.27278322,  0.02571584,  0.13812655, -0.23116972, -0.11188923,
        0.2859863 ,  0.00622673, -0.14631917, -0.13815823, -0.36342928,
        0.04384527, -0.22447421, -0.12952447,  0.03921323,  0.23724791,
       -0.03496383, -0.1800379 , -0.07145933,  0.10016189,  0.21785945,
        0.08639053, -0.19090672, -0.10755674, -0.01982232, -0.06514939,
        0.12248519,  0.10575698,  0.04940713, -0.2627247 ,  0.11888457,
        0.02689304,  0.06878939, -0.05083815, -0.09431162, -0.24472955,
        0.27154124,  0.0938355 ,  0.19120015, -0.30030426,  0.29450679,
       -0.14282939,  0.08876019,  0.25528121, -0.14446004,  0.25285843,
        0.13442759,  0.02112188, -0.05243954, -0.15853426,  0.05804357,
       -0.15549204,  0.01221487, -0.16133857,  0.28532407, -0.13178878,
        0.01866897,  0.10676554,  0.22916363,  0.27780965, -0.02767263,
        0.27771753,  0.12515925,  0.0574971 ,  0.0100568 ,  0.36009046,
        0.22663558,  0.06309903, -0.1868196 ,  0.07759786, -0.05399752])

In [66]:
X[0].shape

(100,)

In [67]:
y

0       0
1       1
2       0
3       0
4       1
       ..
5566    1
5567    0
5568    0
5569    0
5570    0
Name: label, Length: 5571, dtype: int64

In [68]:
X[0].shape

(100,)

In [69]:
X[0].reshape(1,-1).shape

(1, 100)

In [70]:
df=pd.DataFrame(X)

In [71]:
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.151992,0.272414,0.095940,0.036396,0.069818,-0.474774,0.136110,0.434800,-0.185837,-0.102682,...,0.277718,0.125159,0.057497,0.010057,0.360090,0.226636,0.063099,-0.186820,0.077598,-0.053998
1,-0.155456,0.326542,0.133515,0.060887,0.091245,-0.590289,0.171159,0.504241,-0.235242,-0.151866,...,0.317711,0.156159,0.046233,0.020706,0.425065,0.264426,0.049461,-0.238798,0.133350,-0.060440
2,-0.249720,0.432017,0.150731,0.053358,0.109257,-0.728755,0.223166,0.681660,-0.305700,-0.172881,...,0.435531,0.194796,0.092314,0.022030,0.559098,0.369025,0.105060,-0.288165,0.118005,-0.078774
3,-0.218631,0.358952,0.133388,0.043058,0.108034,-0.617835,0.187025,0.580573,-0.258311,-0.155362,...,0.370827,0.156071,0.076702,0.018623,0.465701,0.314223,0.084871,-0.253904,0.103753,-0.074790
4,-0.218907,0.385252,0.142657,0.049825,0.112167,-0.671929,0.200419,0.614442,-0.276946,-0.173329,...,0.389917,0.174264,0.079008,0.017723,0.499235,0.332379,0.082434,-0.266392,0.125783,-0.075644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,-0.192785,0.384478,0.153470,0.057093,0.099735,-0.668411,0.204572,0.587142,-0.264078,-0.177384,...,0.375632,0.178023,0.071473,0.012052,0.503499,0.310665,0.075296,-0.259752,0.136988,-0.073369
5564,-0.221327,0.369102,0.143691,0.056325,0.127325,-0.665088,0.192993,0.610273,-0.280313,-0.161235,...,0.385028,0.172571,0.060012,0.022140,0.494951,0.329269,0.073146,-0.277659,0.126337,-0.068707
5565,-0.249987,0.433281,0.155831,0.040049,0.106241,-0.727526,0.217563,0.677367,-0.296793,-0.183779,...,0.440961,0.199664,0.099155,0.020188,0.565479,0.375205,0.109683,-0.274511,0.123309,-0.090526
5566,-0.218567,0.382589,0.142220,0.045821,0.104091,-0.656990,0.194766,0.603540,-0.270086,-0.167753,...,0.387449,0.173785,0.086904,0.017492,0.502925,0.331533,0.085685,-0.256267,0.117351,-0.079988
5567,-0.244196,0.411833,0.144669,0.050178,0.115150,-0.710577,0.217261,0.665909,-0.303435,-0.181367,...,0.420588,0.183784,0.095209,0.017330,0.544645,0.360736,0.096313,-0.283448,0.133610,-0.076073

In [72]:
y

0       0
1       1
2       0
3       0
4       1
       ..
5566    1
5567    0
5568    0
5569    0
5570    0
Name: label, Length: 5571, dtype: int64

In [73]:
df['label']=y

In [74]:
df

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,label
0,-0.151992,0.272414,0.095940,0.036396,0.069818,-0.474774,0.136110,0.434800,-0.185837,-0.102682,...,0.125159,0.057497,0.010057,0.360090,0.226636,0.063099,-0.186820,0.077598,-0.053998,0
1,-0.155456,0.326542,0.133515,0.060887,0.091245,-0.590289,0.171159,0.504241,-0.235242,-0.151866,...,0.156159,0.046233,0.020706,0.425065,0.264426,0.049461,-0.238798,0.133350,-0.060440,1
2,-0.249720,0.432017,0.150731,0.053358,0.109257,-0.728755,0.223166,0.681660,-0.305700,-0.172881,...,0.194796,0.092314,0.022030,0.559098,0.369025,0.105060,-0.288165,0.118005,-0.078774,0
3,-0.218631,0.358952,0.133388,0.043058,0.108034,-0.617835,0.187025,0.580573,-0.258311,-0.155362,...,0.156071,0.076702,0.018623,0.465701,0.314223,0.084871,-0.253904,0.103753,-0.074790,0
4,-0.218907,0.385252,0.142657,0.049825,0.112167,-0.671929,0.200419,0.614442,-0.276946,-0.173329,...,0.174264,0.079008,0.017723,0.499235,0.332379,0.082434,-0.266392,0.125783,-0.075644,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,-0.192785,0.384478,0.153470,0.057093,0.099735,-0.668411,0.204572,0.587142,-0.264078,-0.177384,...,0.178023,0.071473,0.012052,0.503499,0.310665,0.075296,-0.259752,0.136988,-0.073369,0
5564,-0.221327,0.369102,0.143691,0.056325,0.127325,-0.665088,0.192993,0.610273,-0.280313,-0.161235,...,0.172571,0.060012,0.022140,0.494951,0.329269,0.073146,-0.277659,0.126337,-0.068707,0
5565,-0.249987,0.433281,0.155831,0.040049,0.106241,-0.727526,0.217563,0.677367,-0.296793,-0.183779,...,0.199664,0.099155,0.020188,0.565479,0.375205,0.109683,-0.274511,0.123309,-0.090526,1
5566,-0.218567,0.382589,0.142220,0.045821,0.104091,-0.656990,0.194766,0.603540,-0.270086,-0.167753,...,0.173785,0.086904,0.017492,0.502925,0.331533,0.085685,-0.256267,0.117351,-0.079988,1
5567,-0.244196,0.411833,0.144669,0.050178,0.115150,-0.710577,0.217261,0.665909,-0.303435,-0.181367,...,0.183784,0.095209,0.017330,0.544645,0.360736,0.096313,-0.283448,0.133610,-0.076073,0

In [75]:
X=df.drop('label',axis=1)
y=df['label']

In [76]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [77]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
3918,-0.178380,0.375955,0.152500,0.066449,0.100534,-0.669461,0.187088,0.572826,-0.262420,-0.175678,...,0.365113,0.182901,0.058945,0.022700,0.490192,0.302688,0.058560,-0.263457,0.143611,-0.073191
3986,-0.245928,0.389584,0.142643,0.035579,0.116583,-0.667114,0.197956,0.632377,-0.279886,-0.168508,...,0.408795,0.172382,0.086972,0.015104,0.509447,0.350699,0.099700,-0.264589,0.110480,-0.080788
2758,-0.184133,0.309834,0.117011,0.039592,0.093260,-0.544804,0.162661,0.500843,-0.222873,-0.137189,...,0.324027,0.137838,0.058845,0.013113,0.406498,0.269471,0.068842,-0.220258,0.100682,-0.054798
4796,-0.263854,0.447322,0.160525,0.055683,0.135899,-0.789373,0.233565,0.736831,-0.329146,-0.200031,...,0.462445,0.194644,0.090854,0.020643,0.582289,0.388634,0.091046,-0.320161,0.143383,-0.091292
4503,-0.182953,0.374974,0.152702,0.052143,0.099835,-0.654344,0.183899,0.578490,-0.260079,-0.171712,...,0.370363,0.182446,0.076015,0.019073,0.489857,0.308329,0.079402,-0.253653,0.139219,-0.076259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,-0.211182,0.343573,0.120752,0.041449,0.105457,-0.590638,0.176610,0.553940,-0.237461,-0.137347,...,0.356783,0.153937,0.077336,0.017726,0.456854,0.304620,0.087676,-0.239684,0.092229,-0.070368
5191,-0.206308,0.354450,0.131917,0.043808,0.099034,-0.610497,0.178321,0.566064,-0.245009,-0.143412,...,0.361871,0.159578,0.073949,0.014952,0.462887,0.304883,0.081267,-0.242122,0.099633,-0.068352
5226,-0.229011,0.391055,0.136181,0.034166,0.099603,-0.650432,0.195569,0.606872,-0.269104,-0.159744,...,0.399512,0.180130,0.097729,0.012317,0.511625,0.351753,0.103055,-0.249706,0.114754,-0.091364
5390,-0.242357,0.354736,0.132389,0.030107,0.118167,-0.614320,0.176213,0.588132,-0.260858,-0.160413,...,0.381487,0.141780,0.077475,0.006431,0.447298,0.319950,0.087915,-0.257878,0.091039,-0.066578
860,-0.230443,0.453777,0.163568,0.049523,0.113178,-0.764130,0.230200,0.700448,-0.305387,-0.191330,...,0.454042,0.215694,0.094647,0.020474,0.596274,0.379279,0.101005,-0.280736,0.137891,-0.102134

In [78]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

In [79]:
models={
    "Logistic Regression":LogisticRegression(random_state=42),
    "Decision Tree":DecisionTreeClassifier(random_state=42),
    "Random Forest Classifier":RandomForestClassifier(random_state=42),
    "GradientBoostingClassifier":GradientBoostingClassifier(random_state=42),
    'XGBoost':XGBClassifier(random_state=42)
}

In [80]:
from sklearn.metrics import accuracy_score,classification_report

In [81]:

for name,trained_model in models.items():
    print(f"\n{name} training..\n")

    trained_model.fit(X_train,y_train)

    y_train_pred=trained_model.predict(X_train)
    y_test_pred=trained_model.predict(X_test)

    print("evaluation metrics of train data")
    print("Accuracy: ",accuracy_score(y_train,y_train_pred))
    print("Mean Squared Error",classification_report(y_train,y_train_pred))
    print()
    print("evaluation metrics of test data")
    print("Accuracy: ",accuracy_score(y_test,y_test_pred))
    print("Mean Squared Error",classification_report(y_test,y_test_pred))

    print("-"*40)
    print()

Logistic Regression training..

evaluation metrics of train data
Accuracy:  0.8702290076335878
Mean Squared Error               precision    recall  f1-score   support

           0       0.87      1.00      0.93      3876
           1       0.00      0.00      0.00       578

    accuracy                           0.87      4454
   macro avg       0.44      0.50      0.47      4454
weighted avg       0.76      0.87      0.81      4454


evaluation metrics of test data
Accuracy:  0.8473967684021544
Mean Squared Error               precision    recall  f1-score   support

           0       0.85      1.00      0.92       945
           1       0.00      0.00      0.00       169

    accuracy                           0.85      1114
   macro avg       0.42      0.50      0.46      1114
weighted avg       0.72      0.85      0.78      1114

----------------------------------------


Decision Tree training..

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

evaluation metrics of train data
Accuracy:  0.9806915132465199
Mean Squared Error               precision    recall  f1-score   support

           0       0.98      1.00      0.99      3876
           1       0.99      0.86      0.92       578

    accuracy                           0.98      4454
   macro avg       0.99      0.93      0.95      4454
weighted avg       0.98      0.98      0.98      4454


evaluation metrics of test data
Accuracy:  0.7540394973070018
Mean Squared Error               precision    recall  f1-score   support

           0       0.86      0.85      0.85       945
           1       0.19      0.20      0.19       169

    accuracy                           0.75      1114
   macro avg       0.52      0.52      0.52      1114
weighted avg       0.76      0.75      0.75      1114

----------------------------------------


Random Forest Classifier training..

evaluation metrics of train data
Accuracy:  0.9806915132465199
Mean Squared Error               precision    recall  f1-score   support

           0       0.98      1.00      0.99      3876
           1       0.97      0.88      0.92       578

    accuracy                           0.98      4454
   macro avg       0.98      0.94      0.96      4454
weighted avg       0.98      0.98      0.98      4454


evaluation metrics of test data
Accuracy:  0.8330341113105925
Mean Squared Error               precision    recall  f1-score   support

           0       0.85      0.97      0.91       945
           1       0.26      0.05      0.09       169

    accuracy                           0.83      1114
   macro avg       0.55      0.51      0.50      1114
weighted avg       0.76      0.83      0.78      1114

----------------------------------------


GradientBoostingClassifier training..

evaluation metrics of train data
Accuracy:  0.8875168387965874
Mean Squared Error               precision    recall  f1-score   support

           0       0.89      1.00      0.94      3876
           1       0.98      0.14      0.24       578

    accuracy                           0.89      4454
   macro avg       0.93      0.57      0.59      4454
weighted avg       0.90      0.89      0.85      4454


evaluation metrics of test data
Accuracy:  0.8402154398563735
Mean Squared Error               precision    recall  f1-score   support

           0       0.85      0.98      0.91       945
           1       0.29      0.04      0.06       169

    accuracy                           0.84      1114
   macro avg       0.57      0.51      0.49      1114
weighted avg       0.77      0.84      0.78      1114

----------------------------------------


XGBoost training..

evaluation metrics of train data
Accuracy:  0.9806915132465199
Mean Squared Error               precision    recall  f1-score   support

           0       0.98      1.00      0.99      3876
           1       0.97      0.88      0.92       578

    accuracy                           0.98      4454
   macro avg       0.98      0.94      0.96      4454
weighted avg       0.98      0.98      0.98      4454


evaluation metrics of test data
Accuracy:  0.8204667863554758
Mean Squared Error               precision    recall  f1-score   support

           0       0.85      0.96      0.90       945
           1       0.17      0.05      0.07       169

    accuracy                           0.82      1114
   macro avg       0.51      0.50      0.49      1114
weighted avg       0.75      0.82      0.78      1114

----------------------------------------

In [82]:
models={
    "Random Forest Classifier":RandomForestClassifier(random_state=42),
    "GradientBoostingClassifier":GradientBoostingClassifier(random_state=42),
    'XGBoost':XGBClassifier(random_state=42)
}

In [83]:
from sklearn.model_selection import RandomizedSearchCV

In [84]:

params = {
    "Random Forest Classifier": {
        "n_estimators": [50, 100, 200, 300],
        "max_depth": [None, 5, 10, 20],
        "min_samples_split": [2, 5, 10],
        "min_samples_leaf": [1, 2, 4],
        "max_features": ["auto", "sqrt", "log2"],
        "bootstrap": [True, False]
    },
    "GradientBoostingClassifier": {
        "n_estimators": [100, 200, 300],
        "learning_rate": [0.01, 0.05, 0.1, 0.2],
        "max_depth": [3, 5, 7, 10],
        "min_samples_split": [2, 5, 10],
        "min_samples_leaf": [1, 2, 4],
        "subsample": [0.6, 0.8, 1.0],
        "max_features": ["auto", "sqrt", "log2"]
    },
    "XGBoost": {
        "n_estimators": [100, 200, 300],
        "max_depth": [3, 5, 7, 10],
        "learning_rate": [0.01, 0.05, 0.1, 0.2],
        "subsample": [0.6, 0.8, 1.0],
        "colsample_bytree": [0.6, 0.8, 1.0],
        "gamma": [0, 0.1, 0.3, 0.5],
        "reg_alpha": [0, 0.01, 0.1, 1],
        "reg_lambda": [1, 1.5, 2]
    }
}

In [85]:

for name,model_name in models.items():
    print(f"\n{name} training..\n")

    rs=RandomizedSearchCV(estimator=model_name,param_distributions=params[name],cv=5,n_iter=20,scoring='accuracy',n_jobs=1)
    rs.fit(X_train,y_train)

    y_train_pred=rs.predict(X_train)
    y_test_pred=rs.predict(X_test)

    print("evaluation metrics of train data")
    print("Accuracy: ",accuracy_score(y_train,y_train_pred))
    print("Mean Squared Error",classification_report(y_train,y_train_pred))
    print()
    print("evaluation metrics of test data")
    print("Accuracy: ",accuracy_score(y_test,y_test_pred))
    print("Mean Squared Error",classification_report(y_test,y_test_pred))
    print()

    print("best params:",rs.best_estimator_)
    print("best params:",rs.best_params_)

    print("-"*40)
    print()

Random Forest Classifier training..

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
30 fits failed out of a total of 100.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [0.86080203        nan 0.86147543 0.8554123  0.86102599 0.86933127
 0.85743301 0.86955573        nan        nan 0.86192436 0.86102624
        nan 0.85563601        nan 0.86035234        nan 0.86080152
 0.86461746 0.86349588]
  warnings.warn(

evaluation metrics of train data
Accuracy:  0.8711270767849124
Mean Squared Error               precision    recall  f1-score   support

           0       0.87      1.00      0.93      3876
           1       1.00      0.01      0.01       578

    accuracy                           0.87      4454
   macro avg       0.94      0.50      0.47      4454
weighted avg       0.89      0.87      0.81      4454


evaluation metrics of test data
Accuracy:  0.848294434470377
Mean Squared Error               precision    recall  f1-score   support

           0       0.85      1.00      0.92       945
           1       0.00      0.00      0.00       169

    accuracy                           0.85      1114
   macro avg       0.42      0.50      0.46      1114
weighted avg       0.72      0.85      0.78      1114


best params: RandomForestClassifier(max_depth=5, max_features='log2', min_samples_leaf=4,
                       n_estimators=200, random_state=42)
best params: {'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'log2', 'max_depth': 5, 'bootstrap': True}
----------------------------------------


GradientBoostingClassifier training..

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
45 fits failed out of a total of 100.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of GradientBoostingClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [0.84463587 0.85249297        nan        nan 0.85249297        nan
        nan 0.85810716 0.84463461 0.87022913 0.8509212         nan
        nan 0.85653363 0.85316763 0.8444104  0.85473915        nan
        nan        nan]
  warnings.warn(

evaluation metrics of train data
Accuracy:  0.8702290076335878
Mean Squared Error               precision    recall  f1-score   support

           0       0.87      1.00      0.93      3876
           1       0.00      0.00      0.00       578

    accuracy                           0.87      4454
   macro avg       0.44      0.50      0.47      4454
weighted avg       0.76      0.87      0.81      4454


evaluation metrics of test data
Accuracy:  0.848294434470377
Mean Squared Error               precision    recall  f1-score   support

           0       0.85      1.00      0.92       945
           1       0.00      0.00      0.00       169

    accuracy                           0.85      1114
   macro avg       0.42      0.50      0.46      1114
weighted avg       0.72      0.85      0.78      1114


best params: GradientBoostingClassifier(learning_rate=0.01, max_features='sqrt',
                           min_samples_leaf=2, min_samples_split=10,
                           random_state=42)
best params: {'subsample': 1.0, 'n_estimators': 100, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 3, 'learning_rate': 0.01}
----------------------------------------


XGBoost training..

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

evaluation metrics of train data
Accuracy:  0.8702290076335878
Mean Squared Error               precision    recall  f1-score   support

           0       0.87      1.00      0.93      3876
           1       0.00      0.00      0.00       578

    accuracy                           0.87      4454
   macro avg       0.44      0.50      0.47      4454
weighted avg       0.76      0.87      0.81      4454


evaluation metrics of test data
Accuracy:  0.848294434470377
Mean Squared Error               precision    recall  f1-score   support

           0       0.85      1.00      0.92       945
           1       0.00      0.00      0.00       169

    accuracy                           0.85      1114
   macro avg       0.42      0.50      0.46      1114
weighted avg       0.72      0.85      0.78      1114


best params: XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=0.1, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.01, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=7,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)
best params: {'subsample': 1.0, 'reg_lambda': 1.5, 'reg_alpha': 1, 'n_estimators': 100, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0.1, 'colsample_bytree': 0.8}
----------------------------------------

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [86]:
from sklearn.ensemble import RandomForestClassifier

random_forest=RandomForestClassifier(max_depth=5, min_samples_leaf=4, min_samples_split=10,
                       n_estimators=300, random_state=42)
random_forest.fit(X_train,y_train)

RandomForestClassifier(max_depth=5, min_samples_leaf=4, min_samples_split=10,
                       n_estimators=300, random_state=42)

In [87]:
y_pred=random_forest.predict(X_test)

y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [88]:
from sklearn.metrics import accuracy_score,classification_report

print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8491921005385996
              precision    recall  f1-score   support

           0       0.85      1.00      0.92       945
           1       1.00      0.01      0.01       169

    accuracy                           0.85      1114
   macro avg       0.92      0.50      0.47      1114
weighted avg       0.87      0.85      0.78      1114

In [91]:

def preprocess_input(text):
    # Same preprocessing jo tune corpus pe kiya tha
    text = re.sub('[^a-zA-Z]', ' ', text)
    text = text.lower().split()
    text = [lemmatizer.lemmatize(word) for word in text if word not in stopwords.words('english')]
    return text

def predict_message(text):
    # Step 1: Preprocess
    tokens = preprocess_input(text)
    
    # Step 2: Word2Vec avg vector banana
    vector = avg_wrod2vec(tokens).reshape(1, -1)
    
    # Step 3: Predict
    result = random_forest.predict(vector)[0]
    
    return "SPAM 🚨" if result == 1 else "HAM ✅"


new_message = input("enter message:")
print(predict_message(new_message))

HAM ✅